### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by meadows19** [boy1dr/SpleeterGui#1]
Hello.

When I press "Process" it pops up a command prompt window.
The command prompt stays blank for a long time.
Then it gives this error:

```
Traceback (most recent call last):
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 193, in _run_module_as_main
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 85, in _run_code
  File "C:\Users\Meadows\Desktop\Spleeter_desktop_V1.0\python\Lib\site-packages\spleeter\__main__.py", line 51, in <module>
    entrypoint()
  File "C:\Users\Meadows\Desktop\Spleeter_desktop_V1.0\python\Lib\site-packages\spleeter\__main__.py", line 47, in entrypoint
    main(sys.argv)
  File "C:\Users\Meadows\Desktop\Spleeter_desktop_V1.0\python\Lib\site-packages\spleeter\__main__.py", line 40, in main
    params = load_configuration(arguments.params_filename)
  File "C:\Users\Meadows\Desktop\Spleeter_desktop_V1.0\python\Lib\site-packages\spleeter\utils\configuration.py", line 40, in load_configuration
    raise ValueError(f'No embedded configuration {name} found')
ValueError: No embedded configuration 1stems found
```

What am I doing wrong?

**Comment by boy1dr** [comment]
There's been a couple of people have this issue. Based on the traceback data you provided it appears that there is already python 3.7 installed on D:\obj\windows-release\37amd64_Release\msi_python

I'll see what i can find in regards to a more portable version of python since the version i provided in the zip file and any already installed version seems to cause conflict.

If you're unable to uninstall the existing D: python you may only be able to run the command line version until i find a workaround and post an update.

To install use this command
python3 -m pip install spleeter

To run spleeter use this
python3 -m spleeter separate -i song.mp3 -o output

Let me know if this works for you. i'd like my downloadable version to "just work" :)

**Comment by meadows19** [comment]
Hmm...

Thanks for the super quick response.

The problem is that I don't even have a D drive! Definately no python installed there.
I did try and install Anaconda before so I could run Spleeter, but that failed too. Maybe it's that copy of Python that it's picking up. But it wouldn't be on a D drive.

I'll try to command line commands you posted and let you know. Thank you for that.

**Comment by boy1dr** [comment]
no D: that's weird. perhaps it's a file path left behind by a python developer (i also have no D drive). i'll check out anaconda to see if there's something in there about it. google search shows it to be a common'ish issue with portable versions of python3.7
Thanks for the updated info, gives me something to search for :)

**Comment by boy1dr** [comment]
No solutions found for this issue. latest update has a setting for the python location so different python installs can be tried.
