### ISSUE TITLE
2570444

### ISSUE THREAD

**Issue by 2570444** [boy1dr/SpleeterGui#106]

**Comment by boy1dr** [comment]
Try installing the vcruntime from microsoft 
https://www.microsoft.com/en-au/download/details.aspx?id=48145

**Comment by boy1dr** [comment]
actually, you might need the 64bit version as well.
https://www.microsoft.com/en-us/download/details.aspx?id=52685

**Comment by 2570444** [comment]
Thanks for quick reply, 
my system is 64bit, but it still shows the same error, please help what should i do further ? 

Regards,

**Comment by 2570444** [comment]
[System Config.docx](https://github.com/boy1dr/SpleeterGui/files/6363090/System.Config.docx)

Thanks and regards
K. Abraham Mathai
+919446570444

**Comment by boy1dr** [comment]
So far, the only reasons this DLL Load error occurs is due to AVX support missing or the VC runtime files aren't installed on the machine. You can have a read through a similar issue here https://github.com/boy1dr/SpleeterGui/issues/72
I have also had reports of Spleeter not running on laptop computers.
Your CPU appears to meet the specifications though so i'm not sure why it isn't working for you.
I could give you some commands to try, see if we can't figure it out.

**Comment by boy1dr** [comment]
If you want to give it a try, here's the commands
Click start and type cmd
Run command prompt
Then paste these lines in one by one hitting enter each time.

cd C:\Users\abrah\AppData\Roaming\SpleeterGUI
python\python.exe -W ignore -m spleeter separate -o "c:\temp\output" -d 600 c:\temp\song.mp3

You will need to create those folders and put the song.mp3 in c:\temp

**Comment by 2570444** [comment]
I tried all these , but i am facing the same issues with spleeter GUI,
I have "any desk remote access software"   if you don't mind please do the need full when ever you free,  my WhatsApp +919446570444, 

Thanks and regards.

**Comment by boy1dr** [comment]
Sorry to hear you are having such trouble with it. I won't do a remote desktop thing, i like to keep my distance with other internet users. I am happy to help you through running commands to figure it out though.
If you ran those commands i mentioned earlier can you send me the full output after you ran them?
There must be a reason for Tensorflow trowing the error, we just need to find it.

**Comment by 2570444** [comment]
After I run the system  showing th following error message,,Starting processing of all songs
Processing C:\Temp\abrah\AppData\Roaming\SpleeterGUI\thiruvostiyil vazhum.mp3
Traceback (most recent call last):

File "C:\Temp\abrah\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 64, in
from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed: The specified module could not be found.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 193, in run_module_as_main
File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 85, in run_code
File "C:\Users\abrah\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter_main.py", line 256, in
entrypoint()
File "C:\Temp \abrah\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter_main.py", line 250, in entrypoint
spleeter()
File "C:\Temp\abrah\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\typer\main.py", line 214, in call
return get_command(self)(*args, **kwargs)
File "C:\Temp\abrah\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\click\core.py", line 829, in call
return self.main(*args, **kwargs)
File "C:\Temp\abrah\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\click\core.py", line 782, in main
rv = self.invoke(ctx)
File "C:\Temp\abrah\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\click\core.py", line 1259, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File "C:\Temp\abrah\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\click\core.py", line 1066, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "C:\Temp \abrah\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\click\core.py", line 610, in invoke
return callback(*args, **kwargs)
File "C:\Temp\abrah\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\typer\main.py", line 497, in wrapper

**Comment by 2570444** [comment]
Seems to be my hardware system is not capable to run SpleeterGUI, thanks appreciate to spent your valuable time and good efforts to sort out these kind of problem for our community,  keep it up,
If able to sort it out these problem on SpleeterGUI  setup file in the future, pls let me know,
My plan was to create some Malayalam music ( my mother tongue ) track without VOCALS for a charity music group Named St. Louis Orchestra of the Blind
Thanks and regards, 
K. Abraham Mathai
