### ISSUE TITLE
Error Messages during processing

### ISSUE THREAD

**Issue by Byron1701** [boy1dr/SpleeterGui#110]
"Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\spawn.py", line 99, in spawn_main
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\reduction.py", line 87, in steal_handle
PermissionError: [WinError 5] Access is denied"

Using Windows 7 (I know, I know...) latest version (2.9.1) i7 cpu Dell Precision m6700

Error persists despite move from AppData/Roaming to root C:

Any ideas?

**Comment by boy1dr** [comment]
looks like a file/path issue
put a song in c:\temp, call it song.mp3 and make c:\temp\output for your output.
see if the problem still occurs
