### ISSUE TITLE
Spleeter failing to produce anything now

### ISSUE THREAD

**Issue by mellotronworker** [boy1dr/SpleeterGui#124]
Running the latest version as of right now (22:51 08/09/2021) and Deezer isn't producing anything other than a string of errors, no matter what file or format is supplied to it.  Thi is me trying with 'I Feel Free' by Cream in FLAC format.

Starting processing of all songs
Processing F:\Bands and Artists\Cream\1966 - Fresh Cream [1996 DCC Remaster]\01 - I Feel Free.flac
Traceback (most recent call last):
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 193, in _run_module_as_main
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 85, in _run_code
  File "C:\Users\mike\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 262, in <module>
    entrypoint()
  File "C:\Users\mike\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 256, in entrypoint
    spleeter()
  File "C:\Users\mike\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\typer\main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "C:\Users\mike\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\mike\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Users\mike\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\mike\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\mike\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\mike\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\typer\main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "C:\Users\mike\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 114, in separate
    from .separator import Separator
  File "C:\Users\mike\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\separator.py", line 27, in <module>
    from librosa.core import istft, stft
  File "C:\Users\mike\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\librosa\__init__.py", line 211, in <module>
    from . import core
  File "C:\Users\mike\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\librosa\core\__init__.py", line 5, in <module>
    from .convert import *  # pylint: disable=wildcard-import
  File "C:\Users\mike\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\librosa\core\convert.py", line 7, in <module>
    from . import notation
  File "C:\Users\mike\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\librosa\core\notation.py", line 8, in <module>
    from ..util.exceptions import ParameterError
  File "C:\Users\mike\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\librosa\util\__init__.py", line 83, in <module>
    from .utils import *  # pylint: disable=wildcard-import
  File "C:\Users\mike\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\librosa\util\utils.py", line 10, in <module>
    import numba
  File "C:\Users\mike\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\numba\__init__.py", line 298, in <module>
    import numba.typed
  File "C:\Users\mike\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\numba\typed\__init__.py", line 1, in <module>
    from .typeddict import Dict
  File "C:\Users\mike\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\numba\typed\typeddict.py", line 22, in <module>
    @njit
  File "C:\Users\mike\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\numba\core\decorators.py", line 236, in njit
    return jit(*args, **kws)
  File "C:\Users\mike\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\numba\core\decorators.py", line 173, in jit
    return wrapper(pyfunc)
  File "C:\Users\mike\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\numba\core\decorators.py", line 189, in wrapper
    **dispatcher_args)
  File "C:\Users\mike\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\numba\core\dispatcher.py", line 670, in __init__
    self.targetctx = self.targetdescr.target_context
  File "C:\Users\mike\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\numba\core\registry.py", line 47, in target_context
    return self._toplevel_target_context
  File "C:\Users\mike\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\numba\core\utils.py", line 331, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\mike\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\numba\core\registry.py", line 31, in _toplevel_target_context
    return cpu.CPUContext(self.typing_context)
  File "C:\Users\mike\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\numba\core\base.py", line 259, in __init__
    self.init()
  File "C:\Users\mike\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\numba\core\compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "C:\Users\mike\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\numba\core\cpu.py", line 47, in init
    self._internal_codegen = codegen.JITCPUCodegen("numba.exec")
  File "C:\Users\mike\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\numba\core\codegen.py", line 645, in __init__
    self._init(self._llvm_module)
  File "C:\Users\mike\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\numba\core\codegen.py", line 654, in _init
    tm = target.create_target_machine(**tm_options)
TypeError: create_target_machine() got an unexpected keyword argument 'jitdebug'
Finished processing all songs

Run complete

**Comment by boy1dr** [comment]
@mellotronworker i can confirm this behavior has happened to me to.

You can fix it with a single command.
Click start, type "cmd" and press enter.
Paste the following command and run once you change "chris" to your username
`C:\Users\chris\AppData\Roaming\SpleeterGUI\python>python -m pip install -U llvmlite==0.32.1`

I have raised this as a bug with the spleeter team, hopefully they patch this soon :)

Let's leave this bug open for others that encounter this issue.

**Comment by mellotronworker** [comment]
Good spot - thanks for the update.  Word of warning to others: you'll get a warning about library incompatibility, but it works:

**spleeter 2.3.0 has requirement llvmlite<0.37.0,>=0.36.0, but you'll have llvmlite 0.32.1 which is incompatible.**
Installing collected packages: llvmlite
  Found existing installation: llvmlite 0.36.0
    Uninstalling llvmlite-0.36.0:
      Successfully uninstalled llvmlite-0.36.0
Successfully installed llvmlite-0.32.1

**Comment by cyberlarson** [comment]
boy1dr 
I get an error when running your command

**Comment by boy1dr** [comment]
can you paste the error in here ?

**Comment by cyberlarson** [comment]
the system cannot find the path specified

I've since CD to C:\Users\cyber\AppData\Roaming\SpleeterGUI\python
then pasted this python -m pip install -U llvmlite==0.32.1

But the problem still persists

**Comment by boy1dr** [comment]
Did you run the Spleeter core upgrade?
If so, there are currently issues with the upgrade script that cause it to fail on most windows computers. The easiest fix is to uninstall SpleeterGUI and re-install it.
