### ISSUE TITLE
after upgrading to latest spleeter core, python generates a stack trace and bombs

### ISSUE THREAD

**Issue by RichCaloggero** [boy1dr/SpleeterGui#125]
I've been running this on win7, spleet gui 2.9 just fine. However, today I noticed the "upgrade spleeter core" and tried it; now I can't process anything. Here's the stack trace:

>Starting processing of all songs
Processing C:\Users\Rich\reaper\pickup your hat porchfest\dale's recording\belmont_porchfest_2021.mp3
Traceback (most recent call last):
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 193, in _run_module_as_main
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 85, in _run_code
  File "C:\Users\Rich\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 262, in <module>
    entrypoint()
  File "C:\Users\Rich\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 256, in entrypoint
    spleeter()
  File "C:\Users\Rich\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\typer\main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "C:\Users\Rich\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Rich\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Users\Rich\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Rich\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Rich\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\Rich\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\typer\main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "C:\Users\Rich\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 114, in separate
    from .separator import Separator
  File "C:\Users\Rich\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\separator.py", line 27, in <module>
    from librosa.core import istft, stft
  File "C:\Users\Rich\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\librosa\__init__.py", line 211, in <module>
    from . import core
  File "C:\Users\Rich\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\librosa\core\__init__.py", line 5, in <module>
    from .convert import *  # pylint: disable=wildcard-import
  File "C:\Users\Rich\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\librosa\core\convert.py", line 7, in <module>
    from . import notation
  File "C:\Users\Rich\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\librosa\core\notation.py", line 8, in <module>
    from ..util.exceptions import ParameterError
  File "C:\Users\Rich\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\librosa\util\__init__.py", line 83, in <module>
    from .utils import *  # pylint: disable=wildcard-import
  File "C:\Users\Rich\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\librosa\util\utils.py", line 10, in <module>
    import numba
  File "C:\Users\Rich\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\numba\__init__.py", line 298, in <module>
    import numba.typed
  File "C:\Users\Rich\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\numba\typed\__init__.py", line 1, in <module>
    from .typeddict import Dict
  File "C:\Users\Rich\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\numba\typed\typeddict.py", line 22, in <module>
    @njit
  File "C:\Users\Rich\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\numba\core\decorators.py", line 236, in njit
    return jit(*args, **kws)
  File "C:\Users\Rich\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\numba\core\decorators.py", line 173, in jit
    return wrapper(pyfunc)
  File "C:\Users\Rich\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\numba\core\decorators.py", line 189, in wrapper
    **dispatcher_args)
  File "C:\Users\Rich\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\numba\core\dispatcher.py", line 670, in __init__
    self.targetctx = self.targetdescr.target_context
  File "C:\Users\Rich\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\numba\core\registry.py", line 47, in target_context
    return self._toplevel_target_context
  File "C:\Users\Rich\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\numba\core\utils.py", line 331, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\Rich\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\numba\core\registry.py", line 31, in _toplevel_target_context
    return cpu.CPUContext(self.typing_context)
  File "C:\Users\Rich\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\numba\core\base.py", line 259, in __init__
    self.init()
  File "C:\Users\Rich\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\numba\core\compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "C:\Users\Rich\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\numba\core\cpu.py", line 47, in init
    self._internal_codegen = codegen.JITCPUCodegen("numba.exec")
  File "C:\Users\Rich\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\numba\core\codegen.py", line 645, in __init__
    self._init(self._llvm_module)
  File "C:\Users\Rich\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\numba\core\codegen.py", line 654, in _init
    tm = target.create_target_machine(**tm_options)
TypeError: create_target_machine() got an unexpected keyword argument 'jitdebug'
Finished processing all songs

Run complete

**Comment by boy1dr** [comment]
Please see previous issue https://github.com/boy1dr/SpleeterGui/issues/124
There is a fix to get you going while we wait for Deezer to fix the issue.
