### ISSUE TITLE
The file cannot be generated properly

### ISSUE THREAD

**Issue by RYXMOSES** [boy1dr/SpleeterGui#131]
Traceback (most recent call last):
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 193, in _run_module_as_main
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 85, in _run_code
  File "C:\Users\Moses\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 58, in <module>
    entrypoint()
  File "C:\Users\Moses\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 54, in entrypoint
    main(sys.argv)
  File "C:\Users\Moses\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 40, in main
    from .commands.separate import entrypoint
  File "C:\Users\Moses\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\commands\separate.py", line 15, in <module>
    from ..separator import Separator
  File "C:\Users\Moses\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\separator.py", line 28, in <module>
    from .audio.convertor import to_stereo
  File "C:\Users\Moses\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\audio\convertor.py", line 11, in <module>
    from ..utils.tensor import from_float32_to_uint8, from_uint8_to_float32
  File "C:\Users\Moses\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\utils\tensor.py", line 8, in <module>
    import pandas as pd
  File "C:\Users\Moses\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\pandas\__init__.py", line 55, in <module>
    from pandas.core.api import (
  File "C:\Users\Moses\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\pandas\core\api.py", line 23, in <module>
    from pandas.core.arrays import Categorical, array
  File "C:\Users\Moses\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\pandas\core\arrays\__init__.py", line 10, in <module>
    from .interval import IntervalArray  # noqa: F401
  File "C:\Users\Moses\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\pandas\core\arrays\interval.py", line 38, in <module>
    from pandas.core.indexes.base import Index, ensure_index
  File "C:\Users\Moses\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\pandas\core\indexes\base.py", line 74, in <module>
    from pandas.core.strings import StringMethods
  File "C:\Users\Moses\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\pandas\core\strings\__init__.py", line 30, in <module>
    from pandas.core.strings.accessor import StringMethods
  File "C:\Users\Moses\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\pandas\core\strings\accessor.py", line 16, in <module>
    from pandas._typing import (
ImportError: cannot import name 'DtypeObj' from 'pandas._typing' (C:\Users\Moses\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\pandas\_typing.py)

**Comment by boy1dr** [comment]
There has been some issues with the last few updates from Spleeter, i have managed to get python stable again.
The latest installer 2.9.2 can be found here https://makenweb.com/SpleeterGUI
