### ISSUE TITLE
DLL load failed error?

### ISSUE THREAD

**Issue by Wuvmy3kitties** [boy1dr/SpleeterGui#14]
Hi there, I just started using Spleeter on my Windows 10 64 bit pc, and when I try to process a file this is the result...

  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\imp.py", line 342, in load_dynamic
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.
Failed to load the native TensorFlow runtime.
See https://www.tensorflow.org/install/errors
for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
Finished processing all songs

What should I do?
Thanx in advance :)

**Comment by boy1dr** [comment]
try uninstall / re-install

**Comment by Wuvmy3kitties** [comment]
I uninstalled Spleeter, as well as a version of Anaconda that I had on there before.  Tried reinstalling and still getting the error. (See below)

Starting processing of all songs
Processing C:\Users\Admin\Downloads\Music\xxxx - xxxx.mp3
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Admin\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Admin\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\imp.py", line 242, in load_module
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\imp.py", line 342, in load_dynamic
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 193, in _run_module_as_main
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 85, in _run_code
  File "C:\Users\Admin\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 58, in <module>
    entrypoint()
  File "C:\Users\Admin\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 54, in entrypoint
    main(sys.argv)
  File "C:\Users\Admin\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 36, in main
    enable_logging()
  File "C:\Users\Admin\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\utils\logging.py", line 60, in enable_logging
    tf_logger = get_tensorflow_logger()
  File "C:\Users\Admin\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\utils\logging.py", line 27, in get_tensorflow_logger
    from tensorflow.compat.v1 import logging
  File "C:\Users\Admin\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\tensorflow\__init__.py", line 99, in <module>
    from tensorflow_core import *
  File "C:\Users\Admin\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\tensorflow_core\__init__.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\Admin\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\tensorflow\__init__.py", line 50, in __getattr__
    module = self._load()
  File "C:\Users\Admin\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\tensorflow\__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\__init__.py", line 127, in import_module
  File "C:\Users\Admin\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\tensorflow_core\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\Admin\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Admin\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Admin\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\imp.py", line 242, in load_module
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\imp.py", line 342, in load_dynamic
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.
Failed to load the native TensorFlow runtime.
See https://www.tensorflow.org/install/errors
for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
Finished processing all songs

**Comment by boy1dr** [comment]
This error relates to tensorflow and it seems to vary machine to machine. Google search shows that it might be an issue with previously installed python versions but there's no solid evidence that is the problem.
Spleeter uses Python & Tensorflow, these are very difficult to distribute as a desktop application.
You could try getting python to reinstall the spleeter package, hopefully if there are unmet requirements for your particular machine then the package manager could resolve them.

open a command window and go to the spleeter folder, mine is located here
C:\Users\chris\AppData\Roaming\SpleeterGUI\python
and run the following commands
python -m pip uninstall spleeter
python -m pip install spleeter

**Comment by boy1dr** [comment]
New version 2.5 uploaded yesterday has a spleeter core upgrade feature in the help menu, should help fix issues like these.
https://makenweb.com/spleeter2.php

**Comment by Wuvmy3kitties** [comment]
Sorry but still getting the same errors, even with 2.5 - uninstalled old version and installed this one.

**Comment by boy1dr** [comment]
Hmm that's a shame, i was hoping the python package manager would correct any problems with your install.
What CPU & OS are you running?

**Comment by Wuvmy3kitties** [comment]
I have Windows 10 Pro 64-bit.
Processor is an Intel Core 2 Quad CPU Q8400 2.66GHz
x-64 based processor

**Comment by boy1dr** [comment]
Ahh ok, your CPU may not be recent enough to run tensorflow.
tensorflow is Artificial Intelligence and has only been capable of operating due to advancements in CPU design.
I would recommend Intel Core i5 4th gen or newer.
I didn't create spleeter or tensorflow, i just made the user interface.
Perhaps ask around on some python forums about how to get tensorflow to run on your machine.
You will find python in YOUR appdata folder, mine is
C:\Users\chris\AppData\Roaming\SpleeterGUI\python
