### ISSUE TITLE
ImportError: cannot import name 'DtypeArg' from 'pandas._typing' 

### ISSUE THREAD

**Issue by bopeuph** [boy1dr/SpleeterGui#146]
This is the first time I've seen the error message like this.

Basically, SpleeterGUI runs normally, that error message is just before "finished processing all songs," last message is "run complete," but the files are not outputting.  I have updated to 2.9, and am still getting the same error.

Here's the full process:

Starting processing of all songs
Processing D:\Videos\Aquatic Mouth Dance\Aquatic Mouth Dance.mp3
Traceback (most recent call last):
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 193, in _run_module_as_main
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 85, in _run_code
  File "C:\Users\Nick\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 256, in <module>
    entrypoint()
  File "C:\Users\Nick\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 250, in entrypoint
    spleeter()
  File "C:\Users\Nick\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\typer\main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "C:\Users\Nick\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Nick\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Users\Nick\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Nick\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Nick\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\Nick\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\typer\main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "C:\Users\Nick\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 108, in separate
    from .separator import Separator
  File "C:\Users\Nick\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\separator.py", line 30, in <module>
    from spleeter.model.provider import ModelProvider
  File "C:\Users\Nick\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\model\__init__.py", line 13, in <module>
    from ..utils.tensor import pad_and_partition, pad_and_reshape
  File "C:\Users\Nick\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\utils\tensor.py", line 8, in <module>
    import pandas as pd
  File "C:\Users\Nick\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\pandas\__init__.py", line 142, in <module>
    from pandas.io.api import (
  File "C:\Users\Nick\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\pandas\io\api.py", line 8, in <module>
    from pandas.io.excel import ExcelFile, ExcelWriter, read_excel
  File "C:\Users\Nick\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\pandas\io\excel\__init__.py", line 1, in <module>
    from pandas.io.excel._base import ExcelFile, ExcelWriter, read_excel
  File "C:\Users\Nick\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\pandas\io\excel\_base.py", line 32, in <module>
    from pandas.io.parsers import TextParser
  File "C:\Users\Nick\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\pandas\io\parsers\__init__.py", line 1, in <module>
    from pandas.io.parsers.readers import (
  File "C:\Users\Nick\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\pandas\io\parsers\readers.py", line 17, in <module>
    from pandas._typing import (
ImportError: cannot import name 'DtypeArg' from 'pandas._typing' (C:\Users\Nick\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\pandas\_typing.py)
Finished processing all songs

Run complete

**Comment by boy1dr** [comment]
@bopeuph There has been some issues with the last few updates from Spleeter, i have managed to get python stable again.
The latest installer 2.9.2 can be found here https://makenweb.com/SpleeterGUI
Let me know if you have any dramas

**Comment by Twku** [comment]
I updated to 2.9.2 and the situation is still the same
--------------------------------------------------------------------
開始處理所有歌曲
處理中 D:\Desktop\下載區\愛情你比我想的閣較偉大.mp3
Traceback (most recent call last):
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 193, in _run_module_as_main
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 85, in _run_code
  File "C:\Users\Administrator\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 262, in <module>
    entrypoint()
  File "C:\Users\Administrator\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 256, in entrypoint
    spleeter()
  File "C:\Users\Administrator\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\typer\main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Users\Administrator\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Administrator\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Administrator\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\typer\main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "C:\Users\Administrator\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 114, in separate
    from .separator import Separator
  File "C:\Users\Administrator\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\separator.py", line 30, in <module>
    from spleeter.model.provider import ModelProvider
  File "C:\Users\Administrator\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\model\__init__.py", line 13, in <module>
    from ..utils.tensor import pad_and_partition, pad_and_reshape
  File "C:\Users\Administrator\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\utils\tensor.py", line 8, in <module>
    import pandas as pd
  File "C:\Users\Administrator\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\pandas\__init__.py", line 142, in <module>
    from pandas.io.api import (
  File "C:\Users\Administrator\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\pandas\io\api.py", line 8, in <module>
    from pandas.io.excel import ExcelFile, ExcelWriter, read_excel
  File "C:\Users\Administrator\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\pandas\io\excel\__init__.py", line 1, in <module>
    from pandas.io.excel._base import ExcelFile, ExcelWriter, read_excel
  File "C:\Users\Administrator\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\pandas\io\excel\_base.py", line 32, in <module>
    from pandas.io.parsers import TextParser
  File "C:\Users\Administrator\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\pandas\io\parsers\__init__.py", line 1, in <module>
    from pandas.io.parsers.readers import (
  File "C:\Users\Administrator\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\pandas\io\parsers\readers.py", line 17, in <module>
    from pandas._typing import (
**ImportError: cannot import name 'DtypeArg' from 'pandas._typing' (C:\Users\Administrator\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\pandas\_typing.py)**
結束處理所有歌曲

執行完畢

**Comment by bopeuph** [comment]
> @bopeuph There has been some issues with the last few updates from Spleeter, i have managed to get python stable again. The latest installer 2.9.2 can be found here https://makenweb.com/SpleeterGUI Let me know if you have any dramas

Hi @boy1dr [boy1dr](https://github.com/boy1dr), I finally tried updating, and it didn't help.  I thought if I installed an older version (2.7 since it's the only one still linked on the version history), it might bring back some functionality, but it was giving the same error message.  

I'm assuming it's something with that pandas_typing.py code, but I'm nowhere near good enough of a programmer to address what's going on.  I do assume that replacing pandas_typing.py with a functional file would fix the problem, but I don't know.  Or whatever DtypeArg means.

I ultimately used my laptop to get the file I needed, but there should be a way to do a full clean install, because I think the pertinent files aren't actually being removed from my computer when uninstalling and reinstalling.

**Comment by diego-ruben-cruz** [comment]
Any updates on this? 

I am running into the same problem and attempted multiple reinstallations with no luck.

Here's my trace:
=========================
Starting processing of all songs
Processing C:\Users\Dingo\Desktop\Music\Audio\iTunes\Other\AcceleRacers Soundtrack\06 - Accelorate.mp3
Traceback (most recent call last):
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 193, in _run_module_as_main
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 85, in _run_code
  File "C:\Users\Dingo\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 262, in <module>
    entrypoint()
  File "C:\Users\Dingo\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 256, in entrypoint
    spleeter()
  File "C:\Users\Dingo\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\typer\main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "C:\Users\Dingo\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Dingo\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Users\Dingo\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Dingo\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Dingo\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\Dingo\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\typer\main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "C:\Users\Dingo\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 114, in separate
    from .separator import Separator
  File "C:\Users\Dingo\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\separator.py", line 30, in <module>
    from spleeter.model.provider import ModelProvider
  File "C:\Users\Dingo\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\model\__init__.py", line 13, in <module>
    from ..utils.tensor import pad_and_partition, pad_and_reshape
  File "C:\Users\Dingo\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\utils\tensor.py", line 8, in <module>
    import pandas as pd
  File "C:\Users\Dingo\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\pandas\__init__.py", line 142, in <module>
    from pandas.io.api import (
  File "C:\Users\Dingo\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\pandas\io\api.py", line 8, in <module>
    from pandas.io.excel import ExcelFile, ExcelWriter, read_excel
  File "C:\Users\Dingo\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\pandas\io\excel\__init__.py", line 1, in <module>
    from pandas.io.excel._base import ExcelFile, ExcelWriter, read_excel
  File "C:\Users\Dingo\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\pandas\io\excel\_base.py", line 32, in <module>
    from pandas.io.parsers import TextParser
  File "C:\Users\Dingo\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\pandas\io\parsers\__init__.py", line 1, in <module>
    from pandas.io.parsers.readers import (
  File "C:\Users\Dingo\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\pandas\io\parsers\readers.py", line 17, in <module>
    from pandas._typing import (
ImportError: cannot import name 'DtypeArg' from 'pandas._typing' (C:\Users\Dingo\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\pandas\_typing.py)
Finished processing all songs

Run complete

**Comment by boy1dr** [comment]
Hi @diego-ruben-cruz 

I tried to assemble an updated version over the weekend but ran in to some issues.
The spleeter core update will corrupt the python install every time, the only way to keep the current version running is to not do the core update.

When you uninstall SpleeterGUI make sure this folder is deleted before doing a re-install 

C:\Users\Dingo\AppData\Roaming\SpleeterGUI\

I'll post an update to these github issues when i get python to cooperate

**Comment by diego-ruben-cruz** [comment]
> I tried to assemble an updated version over the weekend but ran into some issues. The Spleeter core update will corrupt the python install every time, the only way to keep the current version running is to not do the core update.
Good to know, I'll keep that in mind going forward until you update.

> When you uninstall SpleeterGUI make sure this folder is deleted before doing a re-install
> C:\Users\Dingo\AppData\Roaming\SpleeterGUI\
> I'll post an update to these GitHub issues when I get python to cooperate
Thanks for the advice, I'll go ahead and run a clean install to see if that plays nice.
