### ISSUE TITLE
BUG:where

### ISSUE THREAD

**Issue by Alec-Menta** [boy1dr/SpleeterGui#147]

**Comment by Alec-Menta** [comment]
After setting all the contents,the output files are not founded in the destination folder
![5C$~`JYJ{_NB7M{@AL2C3{6](https://user-images.githubusercontent.com/67175843/162562069-de9a5782-9eb6-4399-8a2b-a6bc4d5a86ca.png)
like this

**Comment by boy1dr** [comment]
output to desktop does not work
place in to folder

**Comment by Alec-Menta** [comment]
> 

I do place it to folder,however it still does not work

**Comment by boy1dr** [comment]
try changing the music file name to something simple as a test, like song.wav

could you copy paste the output text here? i can't translate the text in the image.
A normal run should look like this...

```
Starting processing of all songs
Processing C:\Users\chris\Music\Friendly\Friendly.mp3
INFO:spleeter:File C:\Users\chris\Desktop\output\Friendly/vocals.wav written succesfully
INFO:spleeter:File C:\Users\chris\Desktop\output\Friendly/accompaniment.wav written succesfully
Finished processing all songs

Run complete
```

**Comment by Alec-Menta** [comment]
> 

I've checked it. It do run normal,just like what you show.

**Comment by boy1dr** [comment]
this issue is same as https://github.com/boy1dr/SpleeterGui/issues/112
does it fail using 2, 4 & 5 stem modes as well?
The solution last time was to delete the spleeter model folders. Spleeter will download them again next time you run it.

try delete these folders
C:\Users\hp1\AppData\Roaming\SpleeterGUI\pretrained_models\2stems
C:\Users\hp1\AppData\Roaming\SpleeterGUI\pretrained_models\4stems
C:\Users\hp1\AppData\Roaming\SpleeterGUI\pretrained_models\5stems

**Comment by Alec-Menta** [comment]
File "C:\Users\hp1\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\tensorflow\python\util\dispatch.py", line 206, in wrapper
    return target(*args, **kwargs)
  File "C:\Users\hp1\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\tensorflow\python\ops\math_ops.py", line 410, in abs
    return gen_math_ops.complex_abs(x, Tout=x.dtype.real_dtype, name=name)
  File "C:\Users\hp1\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\tensorflow\python\ops\gen_math_ops.py", line 2243, in complex_abs
    "ComplexAbs", x=x, Tout=Tout, name=name)
  File "C:\Users\hp1\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\tensorflow\python\framework\op_def_library.py", line 750, in _apply_op_helper
    attrs=attr_protos, op_def=op_def)
  File "C:\Users\hp1\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\tensorflow\python\framework\ops.py", line 3565, in _create_op_internal
    op_def=op_def)
  File "C:\Users\hp1\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\tensorflow\python\framework\ops.py", line 2045, in __init__
    self._traceback = tf_stack.extract_stack_for_node(self._c_op)
Finished processing all songs

Run complete

![2FDJLDS Z7TGP{34{{I`}EK](https://user-images.githubusercontent.com/67175843/162566089-85cf832f-c066-42b2-9db5-31b378aae1a4.png)



it go like this,but I couldn't find such a folder to delete................

**Comment by Alec-Menta** [comment]
Starting processing of all songs
Processing C:\Users\hp1\Desktop\元旦\小虎母带\苏有朋.1994-伤口-飞碟唱片[FLAC]\[苏有朋]情伤.wav
Traceback (most recent call last):
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 193, in _run_module_as_main
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 85, in _run_code
  File "C:\Users\hp1\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 262, in <module>
    entrypoint()
  File "C:\Users\hp1\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 256, in entrypoint
    spleeter()
  File "C:\Users\hp1\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\typer\main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "C:\Users\hp1\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\hp1\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Users\hp1\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\hp1\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\hp1\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\hp1\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\typer\main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "C:\Users\hp1\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 137, in separate
    synchronous=False,
  File "C:\Users\hp1\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\separator.py", line 378, in separate_to_file
    sources = self.separate(waveform, audio_descriptor)
  File "C:\Users\hp1\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\separator.py", line 321, in separate
    return self._separate_librosa(waveform, audio_descriptor)
  File "C:\Users\hp1\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\separator.py", line 260, in _separate_librosa
    stft = self._stft(waveform)
  File "C:\Users\hp1\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\separator.py", line 215, in _stft
    return np.concatenate(out, axis=2 - inverse)
  File "<__array_function__ internals>", line 6, in concatenate
MemoryError: Unable to allocate array with shape (11503, 2049, 2) and data type complex128
Finished processing all songs

Run complete


Now it comes to this..............(

**Comment by boy1dr** [comment]
the error is "MemoryError: Unable to allocate"

Spleeter uses AI which is very memory intensive. You could try reducing the maximum song length
![seconds](https://user-images.githubusercontent.com/5217188/162566772-653cede9-a8ec-4e96-8a3b-12bce1d80786.png)

**Comment by Alec-Menta** [comment]
![5_35XEZAEQS1T@{M%_))0H0](https://user-images.githubusercontent.com/67175843/162567048-218faf98-417d-4afa-bbf6-4b8a2adc69d5.png)

Is it not small enough? The song last about 4.5minutes

**Comment by boy1dr** [comment]
From the error message you have provided, Spleeter is trying to allocate 754 MB of ram and it is failing to do so.

This is not an error that i've seen before.

**Comment by boy1dr** [comment]
(11503 * 2049 * 2) * 128 = 6,033,829,632 bits (754 MB)

**Comment by Alec-Menta** [comment]
Once it has enough ram，it again appears like this：
![YZ`{76} DZ~S5~F46 M05CB](https://user-images.githubusercontent.com/67175843/162574426-a22fd0c2-231c-4eb7-b2a4-dc13dcacdf52.png)

**Comment by pedropachecog** [comment]
I am having the exact same problem. It's the same with 2, 4, and 5 stems. I also tried deleting the model directories.

I'm running Spleeter GUI on Windows 11. I don't have any trouble using previous versions.

<img width="406" alt="SpleeterDoesntWork" src="https://user-images.githubusercontent.com/14306792/171688613-a3fd3216-130a-43ec-8ec5-9082577bfcb3.png">

**Comment by bilibini** [comment]
> Once it has enough ram，it again appears like this： ![YZ`{76} DZS5F46 M05CB](https://user-images.githubusercontent.com/67175843/162574426-a22fd0c2-231c-4eb7-b2a4-dc13dcacdf52.png)

I have the same problem. I found that the audio file length is a problem. The audio file should not exceed 20 minutes
