### ISSUE TITLE
Error 'No such file or directory' after Spleeter core update

### ISSUE THREAD

**Issue by Philizz2** [boy1dr/SpleeterGui#158]
SpleeterGUI 2.6 used to run perfectly until I tried to update Spleeter Core under the Help menu. After this update I get the error posted below, and no new folder or directory is made in my regular Output folder.
I tried uninstalling, installing new version 2.9 of SpleeterGUI, this didn't resolve the issue. 
Uninstalled SpleeterGUI 2.9 again, reboot, install SpleeterGUI 2.6 again (as it used to work for me) - still keep getting the following error:

--

Starting processing of all songs
Processing E:\Philizz\Projects\Yearmix\Yearmix 2022\Mp3 Source\example.mp3
Traceback (most recent call last):
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 193, in _run_module_as_main
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 85, in _run_code
  File "C:\Users\Philizz\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 58, in <module>
    entrypoint()
  File "C:\Users\Philizz\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 54, in entrypoint
    main(sys.argv)
  File "C:\Users\Philizz\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 40, in main
    from .commands.separate import entrypoint
  File "C:\Users\Philizz\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\commands\separate.py", line 15, in <module>
    from ..separator import Separator
  File "C:\Users\Philizz\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\separator.py", line 28, in <module>
    from .audio.convertor import to_stereo
  File "C:\Users\Philizz\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\audio\convertor.py", line 11, in <module>
    from ..utils.tensor import from_float32_to_uint8, from_uint8_to_float32
  File "C:\Users\Philizz\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\utils\tensor.py", line 8, in <module>
    import pandas as pd
  File "C:\Users\Philizz\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\pandas\__init__.py", line 55, in <module>
    from pandas.core.api import (
  File "C:\Users\Philizz\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\pandas\core\api.py", line 23, in <module>
    from pandas.core.arrays import Categorical, array
  File "C:\Users\Philizz\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\pandas\core\arrays\__init__.py", line 10, in <module>
    from .interval import IntervalArray  # noqa: F401
  File "C:\Users\Philizz\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\pandas\core\arrays\interval.py", line 38, in <module>
    from pandas.core.indexes.base import Index, ensure_index
  File "C:\Users\Philizz\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\pandas\core\indexes\base.py", line 74, in <module>
    from pandas.core.strings import StringMethods
  File "C:\Users\Philizz\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\pandas\core\strings\__init__.py", line 30, in <module>
    from pandas.core.strings.accessor import StringMethods
  File "C:\Users\Philizz\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\pandas\core\strings\accessor.py", line 16, in <module>
    from pandas._typing import (
ImportError: cannot import name 'DtypeObj' from 'pandas._typing' (C:\Users\Philizz\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\pandas\_typing.py)
Finished processing all songs

Run complete
ffmpeg version git-2019-11-01-53c21c2 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 9.2.1 (GCC) 20191010
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt --enable-amf
  libavutil      56. 35.101 / 56. 35.101
  libavcodec     58. 60.100 / 58. 60.100
  libavformat    58. 33.100 / 58. 33.100
  libavdevice    58.  9.100 / 58.  9.100
  libavfilter     7. 66.100 /  7. 66.100
  libswscale      5.  6.100 /  5.  6.100
  libswresample   3.  6.100 /  3.  6.100
  libpostproc    55.  6.100 / 55.  6.100
F:\Spleeter\Output\example\bass.wav: No such file or directory

I'm a DJ/editor and not a programming wizard so any help would be greatly appreciated

**Comment by intiperucinema** [comment]
Yes. I've had the same issue on Windows since about December. It just stopped working. It runs - but gives me "No such file or directory". 
Tried a whole lot of fixes with Python and 'Run as Administrator from other threads and checked back every couple of months for updates. Still broken in 2.9.1

Please help. This tool is mostly used by DJs and sound editors that are not technically savvy. It was a godsend while it worked. I had made donations when I could as well.

**Comment by boy1dr** [comment]
The latest Spleeter bundle can be downloaded here
https://makenweb.com/downloads/SpleeterGUI_2.9.2_June24-2022.zip

You will need to extract the zip to the SpleeterGUI folder in your appdata folder.
Mine is located here C:\Users\mitch\AppData\Roaming\SpleeterGUI
replace mitch with your windows username

**Comment by intiperucinema** [comment]
@boy1dr thank you Chris!!! You are a gift to planet earth. Please keep up the good work.

**Comment by intiperucinema** [comment]
Confirming the latest bundle works now! Thank you so much Chris!

**Comment by WALTHER130** [comment]
> El último paquete de Spleeter se puede descargar aquí https://makenweb.com/downloads/SpleeterGUI_2.9.2_June24-2022.zip
> 
> Deberá extraer el zip a la carpeta SpleeterGUI en su carpeta de datos de aplicación. El mío se encuentra aquí C:\Users\mitch\AppData\Roaming\SpleeterGUI reemplaza a mitch con tu nombre de usuario de Windows

Hola. hice ello y no soluciona el problema. O si pudiera especificar un poco más la parte de extraer en la carpeta SPLEETER (Tiene sub carpetas). Agradeceré su respuesta.

**Comment by WALTHER130** [comment]
> ¡Confirmando que el último paquete funciona ahora! ¡Muchas gracias Cris!

Hola. Puedes explicar cómo lo hiciste? Traté de hacerlo y no me funciona.

**Comment by WALTHER130** [comment]
> > ¡Confirmando que el último paquete funciona ahora! ¡Muchas gracias Cris!
> 
> Hola. ¿Puedes explicar cómo lo hiciste? Traté de hacerlo y no me funciona.

**Comment by boy1dr** [comment]
@WALTHER130 The zip file contains replacement files for a broken SpleeterGUI bundle.
You may not see you appdata folder because it is normally hidden. I found a guide here 
`https://support.microsoft.com/en-us/windows/show-hidden-files-0320fe58-0117-fd59-6851-9b7f9840fdb2`

![folder_options](https://user-images.githubusercontent.com/5217188/175800670-a07ad6ac-e680-4d3e-b2f6-9576e635648d.png)

Then you can navigate to the folder, delete these highlighted folders and replace them with the ones from the zip file.
My user account is "mitch", choose your account.

![folder_options2](https://user-images.githubusercontent.com/5217188/175800694-7471abf8-28b3-4f96-86d6-5c65164ff838.png)

**Comment by boy1dr** [comment]
Whenever files go missing from the SpleeterGUI project, it is almost always anti virus removing or quarantining files.
And it usually happens during the install process. The only thing i can suggest is uninstall and re-install as administrator then check your anti virus software isn't messing with the files.

**Comment by sikboy1029** [comment]
started doing this to me too, do you have an update for it again? 

error in the gui

`Starting` processing of all songs
Processing E:\invsddoublefr.wav
Usage: __main__.py separate [OPTIONS] FILES...
Try '__main__.py separate --help' for help.
Error: Missing argument 'FILES...'.
Finished processing all songs

Run complete
ffmpeg version git-2019-11-01-53c21c2 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 9.2.1 (GCC) 20191010
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt --enable-amf
  libavutil      56. 35.101 / 56. 35.101
  libavcodec     58. 60.100 / 58. 60.100
  libavformat    58. 33.100 / 58. 33.100
  libavdevice    58.  9.100 / 58.  9.100
  libavfilter     7. 66.100 /  7. 66.100
  libswscale      5.  6.100 /  5.  6.100
  libswresample   3.  6.100 /  3.  6.100
  libpostproc    55.  6.100 / 55.  6.100
Guessed Channel Layout for Input Stream #0.0 : stereo
Input #0, wav, from 'C:\Users\sikbo\Desktop\New folder (3)\invsddoublefr\vocals.wav':
  Metadata:
    encoder         : Lavf58.33.100
  Duration: 00:09:31.34, bitrate: 1411 kb/s
    Stream #0:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 44100 Hz, stereo, s16, 1411 kb/s
C:\Users\sikbo\Desktop\New folder (3)\invsddoublefr\bass.wav: No such file or `directory`

error in the cmd prompt (did the steps in one of your old posts)

`C:\Users\sikbo\AppData\Roaming\SpleeterGUI>python\python.exe` -W ignore -m spleeter separate -o "c:\temp\output" -d 600 -p "C:\Users\sikbo\AppData\Roaming\SpleeterGUI\config.json" c:\temp\song.wav
Traceback (most recent call last):
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 193, in _run_module_as_main
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 85, in _run_code
  File "C:\Users\sikbo\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 262, in <module>
    entrypoint()
  File "C:\Users\sikbo\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 256, in entrypoint
    spleeter()
  File "C:\Users\sikbo\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\typer\main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "C:\Users\sikbo\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\sikbo\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Users\sikbo\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\sikbo\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\sikbo\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\sikbo\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\typer\main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "C:\Users\sikbo\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 114, in separate
    from .separator import Separator
  File "C:\Users\sikbo\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\separator.py", line 27, in <module>
    from librosa.core import istft, stft
  File "C:\Users\sikbo\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\librosa\__init__.py", line 211, in <module>
    from . import core
  File "C:\Users\sikbo\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\librosa\core\__init__.py", line 5, in <module>
    from .convert import *  # pylint: disable=wildcard-import
  File "C:\Users\sikbo\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\librosa\core\convert.py", line 7, in <module>
    from . import notation
  File "C:\Users\sikbo\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\librosa\core\notation.py", line 8, in <module>
    from ..util.exceptions import ParameterError
  File "C:\Users\sikbo\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\librosa\util\__init__.py", line 83, in <module>
    from .utils import *  # pylint: disable=wildcard-import
  File "C:\Users\sikbo\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\librosa\util\utils.py", line 10, in <module>
    import numba
  File "C:\Users\sikbo\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\numba\__init__.py", line 298, in <module>
    import numba.typed
  File "C:\Users\sikbo\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\numba\typed\__init__.py", line 1, in <module>
    from .typeddict import Dict
  File "C:\Users\sikbo\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\numba\typed\typeddict.py", line 22, in <module>
    @njit
  File "C:\Users\sikbo\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\numba\core\decorators.py", line 236, in njit
    return jit(*args, **kws)
  File "C:\Users\sikbo\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\numba\core\decorators.py", line 173, in jit
    return wrapper(pyfunc)
  File "C:\Users\sikbo\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\numba\core\decorators.py", line 189, in wrapper
    **dispatcher_args)
  File "C:\Users\sikbo\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\numba\core\dispatcher.py", line 670, in __init__
    self.targetctx = self.targetdescr.target_context
  File "C:\Users\sikbo\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\numba\core\registry.py", line 47, in target_context
    return self._toplevel_target_context
  File "C:\Users\sikbo\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\numba\core\utils.py", line 331, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\sikbo\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\numba\core\registry.py", line 31, in _toplevel_target_context
    return cpu.CPUContext(self.typing_context)
  File "C:\Users\sikbo\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\numba\core\base.py", line 259, in __init__
    self.init()
  File "C:\Users\sikbo\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\numba\core\compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "C:\Users\sikbo\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\numba\core\cpu.py", line 47, in init
    self._internal_codegen = codegen.JITCPUCodegen("numba.exec")
  File "C:\Users\sikbo\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\numba\core\codegen.py", line 645, in __init__
    self._init(self._llvm_module)
  File "C:\Users\sikbo\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\numba\core\codegen.py", line 654, in _init
    tm = target.create_target_machine(**tm_options)
TypeError: create_target_machine() got an unexpected keyword argument `'jitdebug'`

**Comment by leopin** [comment]
我使用的最新版本的软件，操作系统和硬件设备也都符合条件，还是出现了同样的错误
