### ISSUE TITLE
2.9.2 spleeter 2.3.2 errors

### ISSUE THREAD

**Issue by dts350z** [boy1dr/SpleeterGui#169]
Starting processing of all songs
Processing E:\GS Spleter\06 - Grey Seal (Remastered 2014).flac
Traceback (most recent call last):
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 193, in _run_module_as_main
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 85, in _run_code
  File "C:\Users\Glenn.THEBEAST\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 262, in <module>
    entrypoint()
  File "C:\Users\Glenn.THEBEAST\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 256, in entrypoint
    spleeter()
  File "C:\Users\Glenn.THEBEAST\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\typer\main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "C:\Users\Glenn.THEBEAST\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Glenn.THEBEAST\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Users\Glenn.THEBEAST\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Glenn.THEBEAST\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Glenn.THEBEAST\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\Glenn.THEBEAST\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\typer\main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "C:\Users\Glenn.THEBEAST\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 114, in separate
    from .separator import Separator
  File "C:\Users\Glenn.THEBEAST\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\separator.py", line 30, in <module>
    from spleeter.model.provider import ModelProvider
  File "C:\Users\Glenn.THEBEAST\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\model\__init__.py", line 13, in <module>
    from ..utils.tensor import pad_and_partition, pad_and_reshape
  File "C:\Users\Glenn.THEBEAST\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\utils\tensor.py", line 8, in <module>
    import pandas as pd
  File "C:\Users\Glenn.THEBEAST\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\pandas\__init__.py", line 142, in <module>
    from pandas.io.api import (
  File "C:\Users\Glenn.THEBEAST\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\pandas\io\api.py", line 8, in <module>
    from pandas.io.excel import ExcelFile, ExcelWriter, read_excel
  File "C:\Users\Glenn.THEBEAST\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\pandas\io\excel\__init__.py", line 1, in <module>
    from pandas.io.excel._base import ExcelFile, ExcelWriter, read_excel
  File "C:\Users\Glenn.THEBEAST\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\pandas\io\excel\_base.py", line 32, in <module>
    from pandas.io.parsers import TextParser
  File "C:\Users\Glenn.THEBEAST\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\pandas\io\parsers\__init__.py", line 1, in <module>
    from pandas.io.parsers.readers import (
  File "C:\Users\Glenn.THEBEAST\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\pandas\io\parsers\readers.py", line 17, in <module>
    from pandas._typing import (
ImportError: cannot import name 'DtypeArg' from 'pandas._typing' (C:\Users\Glenn.THEBEAST\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\pandas\_typing.py)
Finished processing all songs

Run complete

**Comment by boy1dr** [comment]
Had you run the spleeter core update?

Was this your first run?

**Comment by boy1dr** [comment]
"cannot import name 'DtypeArg' from 'pandas._typing'" usually means there has been a python packaging error, typically SpleeterGUI needs to be re-installed.

**Comment by dts350z** [comment]
When I opened SpleaterGUI I had it check for a SpeeterGUI upgrade and it
said 2.9.1 was available. The window is titled 2.9, so I downloaded the
latest (apparently 2.9.2) but the installer wanted to "repair" or "modify",
so thought it was already installed?

I tried modify, and it ran to completion (but the title is still 2.9, and
checking for an update still says 2.9.1 is available).

At that point I probably updated the core, as the changle notes on 2.9.2
said that was working...

Then I tried to run it, and got errors. The run that I posted was not the
first attempt, however.

I guess I can try uninstalling everything and starting over.
