### ISSUE TITLE
Can't load save_path when it is None.

### ISSUE THREAD

**Issue by Ionys320** [boy1dr/SpleeterGui#17]
Bonjour,
Après avoir sélectionné un chemin de sauvegarde et lancé un conversion, j'obtiens une erreur :
```
Starting processing of all songs
Processing C:\Users\Nyan\Music\Pray.mp3
Traceback (most recent call last):
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 193, in _run_module_as_main
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 85, in _run_code
  File "C:\Users\Nyan\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 58, in <module>
    entrypoint()
  File "C:\Users\Nyan\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 54, in entrypoint
    main(sys.argv)
  File "C:\Users\Nyan\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 46, in main
    entrypoint(arguments, params)
  File "C:\Users\Nyan\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\commands\separate.py", line 45, in entrypoint
    synchronous=False
  File "C:\Users\Nyan\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\separator.py", line 217, in separate_to_file
    sources = self.separate(waveform, audio_descriptor)
  File "C:\Users\Nyan\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\separator.py", line 184, in separate
    return self._separate_librosa(waveform, audio_descriptor)
  File "C:\Users\Nyan\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\separator.py", line 169, in _separate_librosa
    saver.restore(sess, latest_checkpoint)
  File "C:\Users\Nyan\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\tensorflow_core\python\training\saver.py", line 1277, in restore
    raise ValueError("Can't load save_path when it is None.")
ValueError: Can't load save_path when it is None.
Finished processing all songs

Run complete
```

**Comment by Ionys320** [comment]
D'accord, j'ai trouvé pourquoi :
Le dossier C:\Users\Nyan\AppData\Roaming\SpleeterGUI\pretrained_models\2stems était vide (Spleeter update core a été fait en même temps que le drag-and-drop.) SpleeterGUI devrait retélécharger le dossier s'il constate qu'il est vide.

**Comment by boy1dr** [comment]
oui, la mise à niveau du noyau spleeter prendra du temps.
Les dossiers 2stem / 4stem / 5stem sont également vides jusqu'à ce que vous exécutiez chacun d'eux et qu'il télécharge les dernières données de modèle.
Mais la mise à niveau et la répétition ne peuvent pas se produire en même temps.

yes the spleeter core upgrade will take a while to run.
Also the 2stem/4stem/5stem folders are empty until you run each one and it downloads the latest model data. 
But upgrade and spleeting cannot occur at the same time.
