### ISSUE TITLE
error spleeter core update

### ISSUE THREAD

**Issue by spicefan25** [boy1dr/SpleeterGui#171]
hello, following the update "spleeter core update" I have this error, despite the reinstallation of spleeter I still have this error, thank you in advance for your help.

Démarrage du traitement de toutes les chansons
En traitement E:\Playlist Fred E\Saint Seiya Soul of God.mp3
Traceback (most recent call last):
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 193, in _run_module_as_main
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 85, in _run_code
  File "C:\Users\SEVEN\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 262, in <module>
    entrypoint()
  File "C:\Users\SEVEN\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 256, in entrypoint
    spleeter()
  File "C:\Users\SEVEN\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\typer\main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "C:\Users\SEVEN\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\SEVEN\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Users\SEVEN\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\SEVEN\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\SEVEN\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\SEVEN\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\typer\main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "C:\Users\SEVEN\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 114, in separate
    from .separator import Separator
  File "C:\Users\SEVEN\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\separator.py", line 30, in <module>
    from spleeter.model.provider import ModelProvider
  File "C:\Users\SEVEN\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\model\__init__.py", line 13, in <module>
    from ..utils.tensor import pad_and_partition, pad_and_reshape
  File "C:\Users\SEVEN\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\utils\tensor.py", line 8, in <module>
    import pandas as pd
  File "C:\Users\SEVEN\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\pandas\__init__.py", line 142, in <module>
    from pandas.io.api import (
  File "C:\Users\SEVEN\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\pandas\io\api.py", line 8, in <module>
    from pandas.io.excel import ExcelFile, ExcelWriter, read_excel
  File "C:\Users\SEVEN\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\pandas\io\excel\__init__.py", line 1, in <module>
    from pandas.io.excel._base import ExcelFile, ExcelWriter, read_excel
  File "C:\Users\SEVEN\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\pandas\io\excel\_base.py", line 32, in <module>
    from pandas.io.parsers import TextParser
  File "C:\Users\SEVEN\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\pandas\io\parsers\__init__.py", line 1, in <module>
    from pandas.io.parsers.readers import (
  File "C:\Users\SEVEN\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\pandas\io\parsers\readers.py", line 17, in <module>
    from pandas._typing import (
ImportError: cannot import name 'DtypeArg' from 'pandas._typing' (C:\Users\SEVEN\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\pandas\_typing.py)
Traitement terminé de toutes les chansons

Exécution terminée

Name: spleeter
Version: 2.3.2

**Comment by boy1dr** [comment]
I have had a few of these recently, happens after a spleeter core update is run.
If you have done a spleeter core update you will need to uninstall SpleeterGUI and re-install it.

**Comment by spicefan25** [comment]
Hi, boy1dr, thank you for your response, i uninstall SpleeterGUI and re-install it, and i have always the same problem
I don't know what else to do except

Starting processing of all songs
Processing E:\Playlist Fred E\Saint Seiya Soul of God.mp3
Traceback (most recent call last):
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 193, in _run_module_as_main
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 85, in _run_code
  File "C:\Users\SEVEN\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 262, in <module>
    entrypoint()
  File "C:\Users\SEVEN\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 256, in entrypoint
    spleeter()
  File "C:\Users\SEVEN\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\typer\main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "C:\Users\SEVEN\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\SEVEN\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Users\SEVEN\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\SEVEN\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\SEVEN\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\SEVEN\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\typer\main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "C:\Users\SEVEN\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 114, in separate
    from .separator import Separator
  File "C:\Users\SEVEN\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\separator.py", line 30, in <module>
    from spleeter.model.provider import ModelProvider
  File "C:\Users\SEVEN\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\model\__init__.py", line 13, in <module>
    from ..utils.tensor import pad_and_partition, pad_and_reshape
  File "C:\Users\SEVEN\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\utils\tensor.py", line 8, in <module>
    import pandas as pd
  File "C:\Users\SEVEN\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\pandas\__init__.py", line 142, in <module>
    from pandas.io.api import (
  File "C:\Users\SEVEN\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\pandas\io\api.py", line 8, in <module>
    from pandas.io.excel import ExcelFile, ExcelWriter, read_excel
  File "C:\Users\SEVEN\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\pandas\io\excel\__init__.py", line 1, in <module>
    from pandas.io.excel._base import ExcelFile, ExcelWriter, read_excel
  File "C:\Users\SEVEN\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\pandas\io\excel\_base.py", line 32, in <module>
    from pandas.io.parsers import TextParser
  File "C:\Users\SEVEN\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\pandas\io\parsers\__init__.py", line 1, in <module>
    from pandas.io.parsers.readers import (
  File "C:\Users\SEVEN\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\pandas\io\parsers\readers.py", line 17, in <module>
    from pandas._typing import (
ImportError: cannot import name 'DtypeArg' from 'pandas._typing' (C:\Users\SEVEN\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\pandas\_typing.py)
Finished processing all songs

Run complete

**Comment by bootlegseahorse** [comment]
> I have had a few of these recently, happens after a spleeter core update is run. If you have done a spleeter core update you will need to uninstall SpleeterGUI and re-install it.

I think there's another workaround. I didn't re-install SpleeterGUI. I just replaced the entire portable python folder with python 3.10, and did the spleeter core update again, then it works like a charm. Yay!

![2022-09-12](https://user-images.githubusercontent.com/97839352/189574746-373fc576-c1ea-45b2-a025-52ff4c165725.png)

**Comment by spicefan25** [comment]
Thank you very much bootlegseahorse, it worked.

**Comment by spicefan25** [comment]
close issue
