### ISSUE TITLE
Updated it to 2.3.2 and now it doesn't process the songs

### ISSUE THREAD

**Issue by ItsJoTa** [boy1dr/SpleeterGui#173]
Starting processing of all songs
Processing D:\Windows\Videos\Local Files Spotify\la novena agregada\La Novena Agregada - De No Serlo (Demo).mp3
Traceback (most recent call last):
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 193, in _run_module_as_main
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 85, in _run_code
  File "C:\Users\JoTa\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 262, in <module>
    entrypoint()
  File "C:\Users\JoTa\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 256, in entrypoint
    spleeter()
  File "C:\Users\JoTa\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\typer\main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "C:\Users\JoTa\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\JoTa\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Users\JoTa\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\JoTa\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\JoTa\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\JoTa\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\typer\main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "C:\Users\JoTa\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 114, in separate
    from .separator import Separator
  File "C:\Users\JoTa\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\separator.py", line 30, in <module>
    from spleeter.model.provider import ModelProvider
  File "C:\Users\JoTa\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\model\__init__.py", line 13, in <module>
    from ..utils.tensor import pad_and_partition, pad_and_reshape
  File "C:\Users\JoTa\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\utils\tensor.py", line 8, in <module>
    import pandas as pd
  File "C:\Users\JoTa\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\pandas\__init__.py", line 142, in <module>
    from pandas.io.api import (
  File "C:\Users\JoTa\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\pandas\io\api.py", line 8, in <module>
    from pandas.io.excel import ExcelFile, ExcelWriter, read_excel
  File "C:\Users\JoTa\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\pandas\io\excel\__init__.py", line 1, in <module>
    from pandas.io.excel._base import ExcelFile, ExcelWriter, read_excel
  File "C:\Users\JoTa\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\pandas\io\excel\_base.py", line 32, in <module>
    from pandas.io.parsers import TextParser
  File "C:\Users\JoTa\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\pandas\io\parsers\__init__.py", line 1, in <module>
    from pandas.io.parsers.readers import (
  File "C:\Users\JoTa\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\pandas\io\parsers\readers.py", line 17, in <module>
    from pandas._typing import (
ImportError: cannot import name 'DtypeArg' from 'pandas._typing' (C:\Users\JoTa\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\pandas\_typing.py)
Finished processing all songs

Run complete

**Comment by boy1dr** [comment]
Howdy

There is a bug somewhere in the python updater, you will need to uninstall and reinstall SpleeterGUI.

I will try to get an update out this weekend to fix these up ;)

**Comment by ItsJoTa** [comment]
> Howdy
> 
> There is a bug somewhere in the python updater, you will need to uninstall and reinstall SpleeterGUI.
> 
> I will try to get an update out this weekend to fix these up ;)

Uninstall it several times didn't change, so I'll wait for the weekend update thx

**Comment by spicefan25** [comment]
Hi ItsJoTa, you can trie that : 

I didn't re-install SpleeterGUI. I just replaced the entire portable python folder with python 3.10, and did the spleeter core update again, then it works like a charm. Yay!
source : bootlegseahorse
![image](https://user-images.githubusercontent.com/73409549/197295115-cf3cf2c5-0c3b-4822-98e4-85d26a662963.png)

**Comment by ItsJoTa** [comment]
nop, didn't work for me maybe bcs the dsi. version I downloaded.

**Comment by boy1dr** [comment]
@spicefan25 How did you manage to get Python3.10 to run as an embeddable version ?

**Comment by spicefan25** [comment]
Hi boy1dr, i download python-3.10.0-amd64.exe at https://www.python.org/downloads/

**Comment by boy1dr** [comment]
@spicefan25 Ahhh, so you ran the exe/installer then copied the python files over to SpleeterGUI?

**Comment by spicefan25** [comment]
Hi, boy1dr, yes :  i run the exe/installer then i copy the python files over to SpleeterGUI and i execute Spleeter core update

**Comment by boy1dr** [comment]
@spicefan25 This method can work...as long as there are no other apps on your system relying on the version of Python that is installed and appears in your system PATH variable.

I'm glad it worked for you and got you up and running again :)

However, for normal use i need to use the Python embeddable version. I grabbed 3.10.8 today but i have been having trouble getting pip to be happy. I remember it wasn't easy with Python2.7 that i currently distribute with SpleeterGUI either.

Hopefully i can get an updated version out this weekend :)

**Comment by boy1dr** [comment]
Hi all

I wasn't able to get the latest python running with spleeter. i will have to step back through the versions until i find a combination that works.

i'll post here when i have a win
