### ISSUE TITLE
SpleeterGui Not Dropping Files Into Folder

### ISSUE THREAD

**Issue by fogle622** [boy1dr/SpleeterGui#179]
Windows 10 Home 22H2 on Dell Inspirion N5040 Intel(R) Core(TM) i3 CPU  M 390  @ 2.67GHz   2.66 GHz with 8 GB ram
SpleeterGUI 2.9.

Receiving import error

Starting processing of all songs
Processing C:\Users\Dell\Desktop\Benson Arizona\Benson Arizona.wav
Traceback (most recent call last):
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 193, in _run_module_as_main
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 85, in _run_code
  File "C:\Users\Dell\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 262, in <module>
    entrypoint()
  File "C:\Users\Dell\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 256, in entrypoint
    spleeter()
  File "C:\Users\Dell\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\typer\main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "C:\Users\Dell\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Dell\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Users\Dell\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Dell\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Dell\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\Dell\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\typer\main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "C:\Users\Dell\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 114, in separate
    from .separator import Separator
  File "C:\Users\Dell\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\separator.py", line 30, in <module>
    from spleeter.model.provider import ModelProvider
  File "C:\Users\Dell\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\model\__init__.py", line 13, in <module>
    from ..utils.tensor import pad_and_partition, pad_and_reshape
  File "C:\Users\Dell\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\utils\tensor.py", line 8, in <module>
    import pandas as pd
  File "C:\Users\Dell\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\pandas\__init__.py", line 142, in <module>
    from pandas.io.api import (
  File "C:\Users\Dell\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\pandas\io\api.py", line 8, in <module>
    from pandas.io.excel import ExcelFile, ExcelWriter, read_excel
  File "C:\Users\Dell\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\pandas\io\excel\__init__.py", line 1, in <module>
    from pandas.io.excel._base import ExcelFile, ExcelWriter, read_excel
  File "C:\Users\Dell\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\pandas\io\excel\_base.py", line 32, in <module>
    from pandas.io.parsers import TextParser
  File "C:\Users\Dell\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\pandas\io\parsers\__init__.py", line 1, in <module>
    from pandas.io.parsers.readers import (
  File "C:\Users\Dell\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\pandas\io\parsers\readers.py", line 17, in <module>
    from pandas._typing import (
ImportError: cannot import name 'DtypeArg' from 'pandas._typing' (C:\Users\Dell\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\pandas\_typing.py)
Finished processing all songs

Run complete

**Comment by trackmaniamatt** [comment]
I had this same issue, but fixed it by doing the following:
1. Uninstall SpleeterGUI
2. Navigate to AppData -> Roaming, and fully delete the SpleeterGUI folder.
3. Reinstalled the latest version of SpleeterGUI (v2.9.2).

After that, I tested, and sure enough, boom!
![success (SpleeterGUI V2 9 2)](https://user-images.githubusercontent.com/19352814/201687222-f94f0f5a-592b-4677-b65b-f53cf1402268.png)

Hope this will be able to help you fix the issue as well! :)
