### ISSUE TITLE
Can you pack the exe or msi as before?

### ISSUE THREAD

**Issue by tranvantruong801** [boy1dr/SpleeterGui#183]
Hi boy1dr, thanks SpleeterGui the software is great. I'm a newbie and I have a few problems that I need your help with. I can't run the SpleeterGui.exe file in the SpleeterGUI_2.9.4.0.zip package like before. I think there is something wrong with python version 3.11.1 in my pc. I wish you in your free time can pack .msi or .exe as before.
Thank you, boy1dr.

**Comment by boy1dr** [comment]
Hi
The installer was too hard to manage so the project is now only available as a standalone folder.
It has it's own python so your system installed python is not used.

What happens when you run the SpleeterGUI.exe ?

**Comment by tranvantruong801** [comment]
Can you re-upload the SpleeterGUI 2.9.2.0.msi file link, I can't explain my problem so I'm kinda shy. I tried finding older versions on google but it's too rare. Path
Version 2.8 https://makenweb.com/downloads/SpleeterGUI_V2.8.msi
Version 2.7 https://makenweb.com/downloads/SpleeterGUI_V2.7.msi is currently not working. I have sent my error information for you to look at. Thank you.
Starting processing of all songs
Processing D:\lastwin\FFBatch\InputVideo.mp4
Traceback (most recent call last):
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 193, in _run_module_as_main
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 85, in _run_code
  File "C:\Users\dmin\Desktop\SpleeterGUI_2.9.4.0\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 262, in <module>
    entrypoint()
  File "C:\Users\dmin\Desktop\SpleeterGUI_2.9.4.0\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 256, in entrypoint
    spleeter()
  File "C:\Users\dmin\Desktop\SpleeterGUI_2.9.4.0\SpleeterGUI\python\Lib\site-packages\typer\main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "C:\Users\dmin\Desktop\SpleeterGUI_2.9.4.0\SpleeterGUI\python\Lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\dmin\Desktop\SpleeterGUI_2.9.4.0\SpleeterGUI\python\Lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Users\dmin\Desktop\SpleeterGUI_2.9.4.0\SpleeterGUI\python\Lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\dmin\Desktop\SpleeterGUI_2.9.4.0\SpleeterGUI\python\Lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\dmin\Desktop\SpleeterGUI_2.9.4.0\SpleeterGUI\python\Lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\dmin\Desktop\SpleeterGUI_2.9.4.0\SpleeterGUI\python\Lib\site-packages\typer\main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "C:\Users\dmin\Desktop\SpleeterGUI_2.9.4.0\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 137, in separate
    synchronous=False,
  File "C:\Users\dmin\Desktop\SpleeterGUI_2.9.4.0\SpleeterGUI\python\Lib\site-packages\spleeter\separator.py", line 376, in separate_to_file
    sample_rate=self._sample_rate,
  File "C:\Users\dmin\Desktop\SpleeterGUI_2.9.4.0\SpleeterGUI\python\Lib\site-packages\spleeter\audio\ffmpeg.py", line 101, in load
    probe = ffmpeg.probe(path)
  File "C:\Users\dmin\Desktop\SpleeterGUI_2.9.4.0\SpleeterGUI\python\Lib\site-packages\ffmpeg\_probe.py", line 24, in probe
    return json.loads(out.decode('utf-8'))
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\__init__.py", line 348, in loads
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\decoder.py", line 337, in decode
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Finished processing all songs

Run complete

**Comment by boy1dr** [comment]
i had to reduce the bandwidth usage on my server so all the links where moved. i will have to delete them soon.
in the meantime you can still get the last msi...just dont run the core update as it breaks the sleepter install.

https://makenweb.com/downloads/old_filezz/SpleeterGUI_V2.9.2.msi

**Comment by tranvantruong801** [comment]
Thank you so much <3
