### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by alanbaiab3** [boy1dr/SpleeterGui#184]
hi there i'm from china so my english is bad.i try to use it but it has a error like this:

Starting processing of all songs
Processing C:\Users\ASUS\Desktop\voice.flac
Traceback (most recent call last):
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 193, in _run_module_as_main
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 85, in _run_code
  File "C:\Users\ASUS\Downloads\SpleeterGUI_2.9.4.0\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 262, in <module>
    entrypoint()
  File "C:\Users\ASUS\Downloads\SpleeterGUI_2.9.4.0\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 256, in entrypoint
    spleeter()
  File "C:\Users\ASUS\Downloads\SpleeterGUI_2.9.4.0\SpleeterGUI\python\Lib\site-packages\typer\main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "C:\Users\ASUS\Downloads\SpleeterGUI_2.9.4.0\SpleeterGUI\python\Lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\ASUS\Downloads\SpleeterGUI_2.9.4.0\SpleeterGUI\python\Lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Users\ASUS\Downloads\SpleeterGUI_2.9.4.0\SpleeterGUI\python\Lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\ASUS\Downloads\SpleeterGUI_2.9.4.0\SpleeterGUI\python\Lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\ASUS\Downloads\SpleeterGUI_2.9.4.0\SpleeterGUI\python\Lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\ASUS\Downloads\SpleeterGUI_2.9.4.0\SpleeterGUI\python\Lib\site-packages\typer\main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "C:\Users\ASUS\Downloads\SpleeterGUI_2.9.4.0\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 137, in separate
    synchronous=False,
  File "C:\Users\ASUS\Downloads\SpleeterGUI_2.9.4.0\SpleeterGUI\python\Lib\site-packages\spleeter\separator.py", line 378, in separate_to_file
    sources = self.separate(waveform, audio_descriptor)
  File "C:\Users\ASUS\Downloads\SpleeterGUI_2.9.4.0\SpleeterGUI\python\Lib\site-packages\spleeter\separator.py", line 321, in separate
    return self._separate_librosa(waveform, audio_descriptor)
  File "C:\Users\ASUS\Downloads\SpleeterGUI_2.9.4.0\SpleeterGUI\python\Lib\site-packages\spleeter\separator.py", line 265, in _separate_librosa
    sess = self._get_session()
  File "C:\Users\ASUS\Downloads\SpleeterGUI_2.9.4.0\SpleeterGUI\python\Lib\site-packages\spleeter\separator.py", line 240, in _get_session
    saver.restore(self._session, latest_checkpoint)
  File "C:\Users\ASUS\Downloads\SpleeterGUI_2.9.4.0\SpleeterGUI\python\Lib\site-packages\tensorflow\python\training\saver.py", line 1291, in restore
    raise ValueError("Can't load save_path when it is None.")
ValueError: Can't load save_path when it is None.
Finished processing all songs

i try to follow the guide that to delete the C:\Users\<yourname>\AppData\Roaming\SpleeterGUI\pretrained_models files. but i didn't find the SpleeterGUI folder.so can anyone help me?

**Comment by boy1dr** [comment]
Hi @alanbaiab3 

The error is "Can't load save_path when it is None."

What is your output path set to ?

Spleeter has trouble reading or writing to some locations, you can try setting output path to c:\output

**Comment by alanbaiab3** [comment]
> 

i tried to set it in c:/output, but it doesn't work and the same problem appear."ValueError: Can't load save_path when it is None."
i followed the way from the help guide "https://makenweb.com/spleeter_help.php", but i can't find the folder which should be in  the "Roaming".i think maybe something of python isn't in the right place?

**Comment by boy1dr** [comment]
this current version 2.9.4 does not install to roaming, it is a simple folder containing all files needed.

Google the error you get and it relates to python not being able to download the training data. do you have something that might block python. maybe try running it as administrator.

If all else fails, try the previous version https://makenweb.com/downloads/old_filezz/SpleeterGUI_V2.9.2.msi

I removed the "spleeter core update" because it was causing problems.
