### ISSUE TITLE
Please tell me how to solve this error

### ISSUE THREAD

**Issue by xiaolang147258** [boy1dr/SpleeterGui#185]
**Please tell me how to solve this error**

Traceback (most recent call last):
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 193, in _run_module_as_main
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 85, in _run_code
  File "D:\dom\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 262, in <module>
    entrypoint()
  File "D:\dom\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 256, in entrypoint
    spleeter()
  File "D:\dom\SpleeterGUI\python\Lib\site-packages\typer\main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "D:\dom\SpleeterGUI\python\Lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "D:\dom\SpleeterGUI\python\Lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "D:\dom\SpleeterGUI\python\Lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "D:\dom\SpleeterGUI\python\Lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\dom\SpleeterGUI\python\Lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "D:\dom\SpleeterGUI\python\Lib\site-packages\typer\main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "D:\dom\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 137, in separate
    synchronous=False,
  File "D:\dom\SpleeterGUI\python\Lib\site-packages\spleeter\separator.py", line 378, in separate_to_file
    sources = self.separate(waveform, audio_descriptor)
  File "D:\dom\SpleeterGUI\python\Lib\site-packages\spleeter\separator.py", line 321, in separate
    return self._separate_librosa(waveform, audio_descriptor)
  File "D:\dom\SpleeterGUI\python\Lib\site-packages\spleeter\separator.py", line 265, in _separate_librosa
    sess = self._get_session()
  File "D:\dom\SpleeterGUI\python\Lib\site-packages\spleeter\separator.py", line 240, in _get_session
    saver.restore(self._session, latest_checkpoint)
  File "D:\dom\SpleeterGUI\python\Lib\site-packages\tensorflow\python\training\saver.py", line 1291, in restore
    raise ValueError("Can't load save_path when it is None.")
ValueError: Can't load save_path when it is None.

**Comment by boy1dr** [comment]
this should help

https://github.com/boy1dr/SpleeterGui/issues/184

**Comment by xiaolang147258** [comment]
thanks
