### ISSUE TITLE
The system cannot access this file.

### ISSUE THREAD

**Issue by ThemanRonin** [boy1dr/SpleeterGui#187]
---------------------------------------------------------------------------
The processor is AMD2700X. WIN10 system. The file path does not contain characters such as Chinese or spaces. The system cannot access this file after running And try to use MP3 music and other formats. The same is true for the administrator to run SpleterGui.exe. The computer is installed with Python version 3.7.9. I want to ask what is this situation?
---------------------------------------------------------------------------
ErrorCode：
開始處理所有歌曲
處理中 X:\SpleeterGUI_2.9.4.0_2\SpleeterGUI\tic.flac
Traceback (most recent call last):
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 193, in _run_module_as_main
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 85, in _run_code
  File "X:\SpleeterGUI_2.9.4.0_2\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 262, in <module>
    entrypoint()
  File "X:\SpleeterGUI_2.9.4.0_2\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 256, in entrypoint
    spleeter()
  File "X:\SpleeterGUI_2.9.4.0_2\SpleeterGUI\python\Lib\site-packages\typer\main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "X:\SpleeterGUI_2.9.4.0_2\SpleeterGUI\python\Lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "X:\SpleeterGUI_2.9.4.0_2\SpleeterGUI\python\Lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "X:\SpleeterGUI_2.9.4.0_2\SpleeterGUI\python\Lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "X:\SpleeterGUI_2.9.4.0_2\SpleeterGUI\python\Lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "X:\SpleeterGUI_2.9.4.0_2\SpleeterGUI\python\Lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "X:\SpleeterGUI_2.9.4.0_2\SpleeterGUI\python\Lib\site-packages\typer\main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "X:\SpleeterGUI_2.9.4.0_2\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 114, in separate
    from .separator import Separator
  File "X:\SpleeterGUI_2.9.4.0_2\SpleeterGUI\python\Lib\site-packages\spleeter\separator.py", line 27, in <module>
    from librosa.core import istft, stft
  File "X:\SpleeterGUI_2.9.4.0_2\SpleeterGUI\python\Lib\site-packages\librosa\__init__.py", line 211, in <module>
    from . import core
  File "X:\SpleeterGUI_2.9.4.0_2\SpleeterGUI\python\Lib\site-packages\librosa\core\__init__.py", line 5, in <module>
    from .convert import *  # pylint: disable=wildcard-import
  File "X:\SpleeterGUI_2.9.4.0_2\SpleeterGUI\python\Lib\site-packages\librosa\core\convert.py", line 7, in <module>
    from . import notation
  File "X:\SpleeterGUI_2.9.4.0_2\SpleeterGUI\python\Lib\site-packages\librosa\core\notation.py", line 8, in <module>
    from ..util.exceptions import ParameterError
  File "X:\SpleeterGUI_2.9.4.0_2\SpleeterGUI\python\Lib\site-packages\librosa\util\__init__.py", line 87, in <module>
    from ._nnls import *  # pylint: disable=wildcard-import
  File "X:\SpleeterGUI_2.9.4.0_2\SpleeterGUI\python\Lib\site-packages\librosa\util\_nnls.py", line 13, in <module>
    import scipy.optimize
  File "X:\SpleeterGUI_2.9.4.0_2\SpleeterGUI\python\Lib\site-packages\scipy\optimize\__init__.py", line 389, in <module>
    from .optimize import *
  File "X:\SpleeterGUI_2.9.4.0_2\SpleeterGUI\python\Lib\site-packages\scipy\optimize\optimize.py", line 37, in <module>
    from .linesearch import (line_search_wolfe1, line_search_wolfe2,
  File "X:\SpleeterGUI_2.9.4.0_2\SpleeterGUI\python\Lib\site-packages\scipy\optimize\linesearch.py", line 18, in <module>
    from scipy.optimize import minpack2
ImportError: DLL load failed: 系统无法访问此文件。
結束處理所有歌曲

執行完畢

**Comment by boy1dr** [comment]
Hi @ThemanRonin 

The error is "DLL load failed", this error is typical of a CPU that does not have the AVX extension so Tensorflow is unable to run.

But i see the AMD 2700X does indeed have AVX support so i am not sure why you are getting this problem. This GUI comes with a packaged version of Python and FFMpeg so you shouldn't need anything else to have it work.

The file path looks fine, FLAC format is supported.

Have you tried running the GUI as administrator ?

Sometimes Windows defender or other anti-virus apps can prevent Python from running correctly.

**Comment by boy1dr** [comment]
Actually, i just translated the last part of the error as "The system cannot access this file" so there is something preventing python from running.

**Comment by ThemanRonin** [comment]
@boy1dr Thank you for your quick reply. I tried to run as an administrator, try to change the installation directory of the Spleter GUI, and change the path of the file music. The permission of the file itself is the administrator's, and there is no inaccessible condition. But the problem remains.
I have installed the installed version of the Spleter GUI before, and then the disk where the Spleter GUI is located is damaged, so I took it away. The SpleterGUI cannot be uninstalled due to lack of disks. This caused the path where the Spleteter GUI was located to be invalid. Is it related to this

**Comment by boy1dr** [comment]
it shouldn't but i will have a look over the code after dinner and let you know
