### ISSUE TITLE
SpleeterGUI v2.9.4.0 (FINAL) released Keeps Rebooting Windows 10

### ISSUE THREAD

**Issue by pn8395** [boy1dr/SpleeterGui#189]
I installed the latest version (v2.9.4.0 (FINAL) but it keeps rebooting the computer during the process of a song.  Does anyone know how to resolve the issue?

**Comment by pn8395** [comment]
This is what I have on the error.  I ran it the first time, the stem folder is downloaded and while it is in the process of extracting the files, the computer is crashed or rebooted.  So I ran the second time, I get the following error:

Starting processing of all songs
Processing C:\Users\pn839\Desktop\Song Name.wav
Traceback (most recent call last):
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 193, in _run_module_as_main
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 85, in _run_code
  File "C:\Users\pn839\Desktop\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 262, in <module>
    entrypoint()
  File "C:\Users\pn839\Desktop\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 256, in entrypoint
    spleeter()
  File "C:\Users\pn839\Desktop\SpleeterGUI\python\Lib\site-packages\typer\main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "C:\Users\pn839\Desktop\SpleeterGUI\python\Lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\pn839\Desktop\SpleeterGUI\python\Lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Users\pn839\Desktop\SpleeterGUI\python\Lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\pn839\Desktop\SpleeterGUI\python\Lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\pn839\Desktop\SpleeterGUI\python\Lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\pn839\Desktop\SpleeterGUI\python\Lib\site-packages\typer\main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "C:\Users\pn839\Desktop\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 137, in separate
    synchronous=False,
  File "C:\Users\pn839\Desktop\SpleeterGUI\python\Lib\site-packages\spleeter\separator.py", line 378, in separate_to_file
    sources = self.separate(waveform, audio_descriptor)
  File "C:\Users\pn839\Desktop\SpleeterGUI\python\Lib\site-packages\spleeter\separator.py", line 321, in separate
    return self._separate_librosa(waveform, audio_descriptor)
  File "C:\Users\pn839\Desktop\SpleeterGUI\python\Lib\site-packages\spleeter\separator.py", line 265, in _separate_librosa
    sess = self._get_session()
  File "C:\Users\pn839\Desktop\SpleeterGUI\python\Lib\site-packages\spleeter\separator.py", line 240, in _get_session
    saver.restore(self._session, latest_checkpoint)
  File "C:\Users\pn839\Desktop\SpleeterGUI\python\Lib\site-packages\tensorflow\python\training\saver.py", line 1291, in restore
    raise ValueError("Can't load save_path when it is None.")
ValueError: Can't load save_path when it is None.
Finished processing all songs

Run complete

**Comment by boy1dr** [comment]
A rebooting computer sounds like a memory or driver issue. You can check your windows event log after it reboots there will most likely be information there about what happened.

Spleeter is a Python application which will download the pre-trained model data automatically the first time you run it. You may need to delete the stems folders and try again as the download may have corrupted the first time around.

![spleeter_folder](https://user-images.githubusercontent.com/5217188/220462077-70ca0bf7-a779-4d6a-b72f-45ac6c6d631b.jpg)

Antivirus/Defender is also known to interfere with Python downloading things so it may be necessary to run SpleeterGUI as administrator at least once.

Another user had this problem a few days ago, i left the issue open in case it can help others like yourself. If you still have issues getting those pretrained model files you can manually download them and place them in the SpleeterGUI folder, instructions are https://github.com/boy1dr/SpleeterGui/issues/188

**Comment by pn8395** [comment]
I've tried again and turned off the Windows Defender, but got result.  So I uninstalled the Final Version 2.9..4 and reinstall a lower version 2.9.2.  When run it, I get this error "Unhandled exception has occurred in your application... The given key was not present in the dictionary"

![2023-02-26_15-14-07](https://user-images.githubusercontent.com/125764758/221434952-ffc7fd48-d8c7-43bb-aa38-2f505b2fe54e.jpg)

**Comment by boy1dr** [comment]
Hmm it would appear that i have overlooked some problematic code. I'll have a look at it tonight and see if i can get a patch up for it.
