### ISSUE TITLE
I don't know if the processing is finished, but I can't find the separated audio files anyway.

### ISSUE THREAD

**Issue by sechsy** [boy1dr/SpleeterGui#191]
開始處理所有歌曲
處理中 C:\Users\Administrator\Desktop\2月22日.mp3
Traceback (most recent call last):
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 193, in _run_module_as_main
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 85, in _run_code
  File "D:\Program Files(x86)\SpleeterGUI\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 262, in <module>
    entrypoint()
  File "D:\Program Files(x86)\SpleeterGUI\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 256, in entrypoint
    spleeter()
  File "D:\Program Files(x86)\SpleeterGUI\SpleeterGUI\python\Lib\site-packages\typer\main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "D:\Program Files(x86)\SpleeterGUI\SpleeterGUI\python\Lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "D:\Program Files(x86)\SpleeterGUI\SpleeterGUI\python\Lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "D:\Program Files(x86)\SpleeterGUI\SpleeterGUI\python\Lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "D:\Program Files(x86)\SpleeterGUI\SpleeterGUI\python\Lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\Program Files(x86)\SpleeterGUI\SpleeterGUI\python\Lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "D:\Program Files(x86)\SpleeterGUI\SpleeterGUI\python\Lib\site-packages\typer\main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "D:\Program Files(x86)\SpleeterGUI\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 137, in separate
    synchronous=False,
  File "D:\Program Files(x86)\SpleeterGUI\SpleeterGUI\python\Lib\site-packages\spleeter\separator.py", line 378, in separate_to_file
    sources = self.separate(waveform, audio_descriptor)
  File "D:\Program Files(x86)\SpleeterGUI\SpleeterGUI\python\Lib\site-packages\spleeter\separator.py", line 321, in separate
    return self._separate_librosa(waveform, audio_descriptor)
  File "D:\Program Files(x86)\SpleeterGUI\SpleeterGUI\python\Lib\site-packages\spleeter\separator.py", line 265, in _separate_librosa
    sess = self._get_session()
  File "D:\Program Files(x86)\SpleeterGUI\SpleeterGUI\python\Lib\site-packages\spleeter\separator.py", line 240, in _get_session
    saver.restore(self._session, latest_checkpoint)
  File "D:\Program Files(x86)\SpleeterGUI\SpleeterGUI\python\Lib\site-packages\tensorflow\python\training\saver.py", line 1291, in restore
    raise ValueError("Can't load save_path when it is None.")
ValueError: Can't load save_path when it is None.
結束處理所有歌曲

**Comment by boy1dr** [comment]
please see previous issue https://github.com/boy1dr/SpleeterGui/issues/189

or 188

**Comment by sechsy** [comment]
I followed your instruction, deleted the 2steam file, then restarted the computer system and rebooted it, run the software as administrator, but still could not separate the audio file or even find the exported audio file, what can I do now? I am using a Win7 64-bit system, so I can't use such a great software design？

**Comment by sechsy** [comment]
Still can not come out to help me

**Comment by boy1dr** [comment]
@sechsy It's not usually this hard to run the software as long as your computer is capable of it.

Sorry that you are having a bad time, lets see if one of these suggestions helps you out.

Your CPU must support the AVX instruction, i made an AVX test application that will give you a simple yes or no, it can be downloaded here https://makenweb.com/downloads/AVXcheck.zip

More information about AVX is on my site https://makenweb.com/#avxcheck

If you get a "yes" from the AVX check, try removing the current SpleeterGUI version and install the last full installer i made https://makenweb.com/downloads/old_filezz/SpleeterGUI_V2.9.2.msi

If you get a "no" from AVX check then i'm sorry but your computer isn't able to run Spleeter. Most laptops and older machines will lack the AVX instruction that allows AI to function, it's pretty new.

That SpleeterGUI download is for version 2.9.2 which is an older version of Spleeter but it also contains the model files you seem to be having trouble downloading. It is a bigger download because of the pretrained model files.

**Comment by sechsy** [comment]
![QQ图片20230225143029](https://user-images.githubusercontent.com/120312181/221342456-67b14b44-5db4-458f-ab3f-96625d7f9171.png)

**Comment by sechsy** [comment]
![QQ图片20230225145251](https://user-images.githubusercontent.com/120312181/221343311-2474a52e-7696-4907-af2c-c81e9acc5a4f.png)

**Comment by boy1dr** [comment]
We had a win ?

**Comment by sechsy** [comment]
I don't know why, but I actually succeeded. I'm so happy because you made some adjustments right? It feels like hitting the jackpot. Thank you. I was so excited that I jumped up and down on the spot. Instantly felt like there was nothing wrong with my computer. Can I ask you another question about another area? I have some SRT subtitle files and I want to make it synthesize audio files, something like reading out the subtitles into downloadable audio or something like that. Of course, it doesn't have to be an area you're familiar with, but if you can answer that would be great. Because I think you're great.

**Comment by sechsy** [comment]
You have this SpleeterGui audio separation software, which is very popular on YouTube. Many people are admiring it and I've been frustrated for the first few days because I couldn't use it, so thank you for your company and technical support these days.

**Comment by boy1dr** [comment]
The difference between 2.9.2 and 2.9.4 is that i removed the pretrained model files from the newer version to save a bit of bandwidth, but that means the end user needs to download them and since SpleeterGUI is a windows executable launching a python application that downloads something it can be seen malicious and stopped by defender or antivirus. total pain in the butt.

I'm not sure what you mean about synthesizing subtitle tracks but there are text-to-speech sites out there that will provide you with audio files, some even AI generated. The freeware linux one (eSpeak) isn't great. Just google (ai text to speech) and you will find plenty of options.

And no worries with the support. if i have time i will jump in and solve issues :)

**Comment by sechsy** [comment]
I also tried to use AI, but I can't go through the generation of audio based on the timeline. This one bothers me more. But thank you very much and good luck with your work. (The srt subtitles are similar to this image. The generated audio also needs the corresponding time interval)
![QQ图片20230225151108](https://user-images.githubusercontent.com/120312181/221344104-29c304a2-f158-49c0-9bcf-afbb1af85955.png)

**Comment by sechsy** [comment]
![QQ图片20230225150928](https://user-images.githubusercontent.com/120312181/221344117-9b0bcb61-d74c-4a85-9062-554adca05aef.png)
