### ISSUE TITLE
MemoryError: Unable to allocate array with shape (307499, 2049, 2) and data type complex128

### ISSUE THREAD

**Issue by Florria2** [boy1dr/SpleeterGui#194]
Traceback (most recent call last):
File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 193, in run_module_as_main
File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 85, in run_code
File "E:\SpleeterGUI\python\Lib\site-packages\spleeter_main.py", line 262, in
entrypoint()
File "E:\SpleeterGUI\python\Lib\site-packages\spleeter_main.py", line 256, in entrypoint
spleeter()
File "E:\SpleeterGUI\python\Lib\site-packages\typer\main.py", line 214, in call
return get_command(self)(*args, **kwargs)
File "E:\SpleeterGUI\python\Lib\site-packages\click\core.py", line 829, in call
return self.main(*args, **kwargs)
File "E:\SpleeterGUI\python\Lib\site-packages\click\core.py", line 782, in main
rv = self.invoke(ctx)
File "E:\SpleeterGUI\python\Lib\site-packages\click\core.py", line 1259, in invoke
return process_result(sub_ctx.command.invoke(sub_ctx))
File "E:\SpleeterGUI\python\Lib\site-packages\click\core.py", line 1066, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "E:\SpleeterGUI\python\Lib\site-packages\click\core.py", line 610, in invoke
return callback(*args, **kwargs)
File "E:\SpleeterGUI\python\Lib\site-packages\typer\main.py", line 497, in wrapper
return callback(**use_params) # type: ignore
File "E:\SpleeterGUI\python\Lib\site-packages\spleeter_main.py", line 137, in separate
synchronous=False,
File "E:\SpleeterGUI\python\Lib\site-packages\spleeter\separator.py", line 378, in separate_to_file
sources = self.separate(waveform, audio_descriptor)
File "E:\SpleeterGUI\python\Lib\site-packages\spleeter\separator.py", line 321, in separate
return self._separate_librosa(waveform, audio_descriptor)
File "E:\SpleeterGUI\python\Lib\site-packages\spleeter\separator.py", line 260, in _separate_librosa
stft = self._stft(waveform)
File "E:\SpleeterGUI\python\Lib\site-packages\spleeter\separator.py", line 215, in _stft
return np.concatenate(out, axis=2 - inverse)
File "<array_function internals>", line 6, in concatenate
MemoryError: Unable to allocate array with shape (307499, 2049, 2) and data type complex128

![图片](https://user-images.githubusercontent.com/128038240/226253312-8b73ca75-c58f-4d92-9d9c-71bd06ade252.png)

An error occurred when extracting audio with a duration of 90 minutes. How to solve it?

**Comment by boy1dr** [comment]
Hi

Spleeter uses a LOT of memory, this error means you ran out of memory trying to process the file.

Your options are to install a lot more system memory or split your audio in to smaller chunks and process them separately.
