### ISSUE TITLE
Error: Can't load save_path when it is None.

### ISSUE THREAD

**Issue by nottellyou** [boy1dr/SpleeterGui#199]
Hi,  The SpleeterGui encountered an error while working and could not separate the music.
The infomation:
```
Starting processing of all songs
Processing F:\temp_files\au\22222222.wav
Traceback (most recent call last):
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 193, in _run_module_as_main
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 85, in _run_code
  File "E:\AI\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 262, in <module>
    entrypoint()
  File "E:\AI\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 256, in entrypoint
    spleeter()
  File "E:\AI\SpleeterGUI\python\Lib\site-packages\typer\main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "E:\AI\SpleeterGUI\python\Lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "E:\AI\SpleeterGUI\python\Lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "E:\AI\SpleeterGUI\python\Lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "E:\AI\SpleeterGUI\python\Lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "E:\AI\SpleeterGUI\python\Lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "E:\AI\SpleeterGUI\python\Lib\site-packages\typer\main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "E:\AI\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 137, in separate
    synchronous=False,
  File "E:\AI\SpleeterGUI\python\Lib\site-packages\spleeter\separator.py", line 378, in separate_to_file
    sources = self.separate(waveform, audio_descriptor)
  File "E:\AI\SpleeterGUI\python\Lib\site-packages\spleeter\separator.py", line 321, in separate
    return self._separate_librosa(waveform, audio_descriptor)
  File "E:\AI\SpleeterGUI\python\Lib\site-packages\spleeter\separator.py", line 265, in _separate_librosa
    sess = self._get_session()
  File "E:\AI\SpleeterGUI\python\Lib\site-packages\spleeter\separator.py", line 240, in _get_session
    saver.restore(self._session, latest_checkpoint)
  File "E:\AI\SpleeterGUI\python\Lib\site-packages\tensorflow\python\training\saver.py", line 1291, in restore
    raise ValueError("Can't load save_path when it is None.")
ValueError: Can't load save_path when it is None.
Finished processing all songs

Run complete
```

Note: There is no this path `D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py` on my disk. 

version: 2.9.4.0
CPU: I5-6200u
os_ver: win7_x64

**Comment by boy1dr** [comment]
Thanks for including the full error.

That weird D:\ path is baked in to the code, not the problem.

The source folder looks ok, what's your save path?

**Comment by boy1dr** [comment]
That was my next guess. Your save path looks fine.

Python will do a download of the model files the first time you each stem mode, something must be blocking it.

You can try running SpleeterGUI with administrative privileges, or use the older larger installer. Let me know if you can't find that link.

**Comment by nottellyou** [comment]
Thinks  @boy1dr

**Comment by wei-z-git** [comment]
I have the same issue even I run with admin privileges, it seems it didn`t download the models...
So I just download these models(https://github.com/deezer/spleeter/releases) into `\SpleeterGUI\pretrained_models` manually...
