### ISSUE TITLE
Some runtime error. How to solve?

### ISSUE THREAD

**Issue by qingdkj** [boy1dr/SpleeterGui#205]
line 85, in _run_code
  File "S:\SpleeterGUI_2.9.4.0\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 262, in <module>
    entrypoint()
  File "S:\SpleeterGUI_2.9.4.0\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 256, in entrypoint
    spleeter()
  File "S:\SpleeterGUI_2.9.4.0\SpleeterGUI\python\Lib\site-packages\typer\main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "S:\SpleeterGUI_2.9.4.0\SpleeterGUI\python\Lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "S:\SpleeterGUI_2.9.4.0\SpleeterGUI\python\Lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "S:\SpleeterGUI_2.9.4.0\SpleeterGUI\python\Lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "S:\SpleeterGUI_2.9.4.0\SpleeterGUI\python\Lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "S:\SpleeterGUI_2.9.4.0\SpleeterGUI\python\Lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "S:\SpleeterGUI_2.9.4.0\SpleeterGUI\python\Lib\site-packages\typer\main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "S:\SpleeterGUI_2.9.4.0\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 137, in separate
    synchronous=False,
  File "S:\SpleeterGUI_2.9.4.0\SpleeterGUI\python\Lib\site-packages\spleeter\separator.py", line 378, in separate_to_file
    sources = self.separate(waveform, audio_descriptor)
  File "S:\SpleeterGUI_2.9.4.0\SpleeterGUI\python\Lib\site-packages\spleeter\separator.py", line 321, in separate
    return self._separate_librosa(waveform, audio_descriptor)
  File "S:\SpleeterGUI_2.9.4.0\SpleeterGUI\python\Lib\site-packages\spleeter\separator.py", line 265, in _separate_librosa
    sess = self._get_session()
  File "S:\SpleeterGUI_2.9.4.0\SpleeterGUI\python\Lib\site-packages\spleeter\separator.py", line 240, in _get_session
    saver.restore(self._session, latest_checkpoint)
  File "S:\SpleeterGUI_2.9.4.0\SpleeterGUI\python\Lib\site-packages\tensorflow\python\training\saver.py", line 1291, in restore
    raise ValueError("Can't load save_path when it is None.")
ValueError: Can't load save_path when it is None.
Finished processing all songs

Run complete

**Comment by kongwx999** [comment]
Traceback (most recent call last):
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 193, in _run_module_as_main
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 85, in _run_code
  File "C:\SpleeterGUI_2.9.4.0\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 262, in <module>
    entrypoint()
  File "C:\SpleeterGUI_2.9.4.0\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 256, in entrypoint
    spleeter()
  File "C:\SpleeterGUI_2.9.4.0\SpleeterGUI\python\Lib\site-packages\typer\main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "C:\SpleeterGUI_2.9.4.0\SpleeterGUI\python\Lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\SpleeterGUI_2.9.4.0\SpleeterGUI\python\Lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\SpleeterGUI_2.9.4.0\SpleeterGUI\python\Lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\SpleeterGUI_2.9.4.0\SpleeterGUI\python\Lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\SpleeterGUI_2.9.4.0\SpleeterGUI\python\Lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\SpleeterGUI_2.9.4.0\SpleeterGUI\python\Lib\site-packages\typer\main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "C:\SpleeterGUI_2.9.4.0\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 137, in separate
    synchronous=False,
  File "C:\SpleeterGUI_2.9.4.0\SpleeterGUI\python\Lib\site-packages\spleeter\separator.py", line 378, in separate_to_file
    sources = self.separate(waveform, audio_descriptor)
  File "C:\SpleeterGUI_2.9.4.0\SpleeterGUI\python\Lib\site-packages\spleeter\separator.py", line 321, in separate
    return self._separate_librosa(waveform, audio_descriptor)
  File "C:\SpleeterGUI_2.9.4.0\SpleeterGUI\python\Lib\site-packages\spleeter\separator.py", line 265, in _separate_librosa
    sess = self._get_session()
  File "C:\SpleeterGUI_2.9.4.0\SpleeterGUI\python\Lib\site-packages\spleeter\separator.py", line 240, in _get_session
    saver.restore(self._session, latest_checkpoint)
  File "C:\SpleeterGUI_2.9.4.0\SpleeterGUI\python\Lib\site-packages\tensorflow\python\training\saver.py", line 1291, in restore
    raise Value Error("Can't load save_path when it is None.")
ValueError: Can't load save_path when it is None.

**Comment by kongwx999** [comment]
@sechsy It's not usually this hard to run the software as long as your computer is capable of it.

Sorry that you are having a bad time, lets see if one of these suggestions helps you out.

Your CPU must support the AVX instruction, i made an AVX test application that will give you a simple yes or no, it can be downloaded here https://makenweb.com/downloads/AVXcheck.zip

More information about AVX is on my site https://makenweb.com/#avxcheck

If you get a "yes" from the AVX check, try removing the current SpleeterGUI version and install the last full installer i made https://makenweb.com/downloads/old_filezz/SpleeterGUI_V2.9.2.msi

If you get a "no" from AVX check then i'm sorry but your computer isn't able to run Spleeter. Most laptops and older machines will lack the AVX instruction that allows AI to function, it's pretty new.

That SpleeterGUI download is for version 2.9.2 which is an older version of Spleeter but it also contains the model files you seem to be having trouble downloading. It is a bigger download because of the pretrained model files.
