### ISSUE TITLE
[Help] ValueError: Can't load save_path when it is None

### ISSUE THREAD

**Issue by Rexadev** [boy1dr/SpleeterGui#215]
```
Starting processing of all songs
Processing D:\SpleeterGUI_2.9.4.0\SpleeterGUI\Test.mp3
Usage: __main__.py separate [OPTIONS] FILES...
Try '__main__.py separate --help' for help.
Error: Missing argument 'FILES...'.
Finished processing all songs

Run complete
```
![image](https://github.com/boy1dr/SpleeterGui/assets/62152714/66763a50-5aa2-459c-96d9-c6519dd32f42)

**Comment by boy1dr** [comment]
For some reason, Spleeter doesn't like outputting to a root folder like "D:\"
Try "D:\output" that should work better.

**Comment by Rexadev** [comment]
```
Starting processing of all songs
Processing D:\SpleeterGUI_2.9.4.0\Test.mp3
Traceback (most recent call last):
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 193, in _run_module_as_main
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 85, in _run_code
  File "D:\SpleeterGUI_2.9.4.0\python\Lib\site-packages\spleeter\__main__.py", line 262, in <module>
    entrypoint()
  File "D:\SpleeterGUI_2.9.4.0\python\Lib\site-packages\spleeter\__main__.py", line 256, in entrypoint
    spleeter()
  File "D:\SpleeterGUI_2.9.4.0\python\Lib\site-packages\typer\main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "D:\SpleeterGUI_2.9.4.0\python\Lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "D:\SpleeterGUI_2.9.4.0\python\Lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "D:\SpleeterGUI_2.9.4.0\python\Lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "D:\SpleeterGUI_2.9.4.0\python\Lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\SpleeterGUI_2.9.4.0\python\Lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "D:\SpleeterGUI_2.9.4.0\python\Lib\site-packages\typer\main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "D:\SpleeterGUI_2.9.4.0\python\Lib\site-packages\spleeter\__main__.py", line 137, in separate
    synchronous=False,
  File "D:\SpleeterGUI_2.9.4.0\python\Lib\site-packages\spleeter\separator.py", line 378, in separate_to_file
    sources = self.separate(waveform, audio_descriptor)
  File "D:\SpleeterGUI_2.9.4.0\python\Lib\site-packages\spleeter\separator.py", line 321, in separate
    return self._separate_librosa(waveform, audio_descriptor)
  File "D:\SpleeterGUI_2.9.4.0\python\Lib\site-packages\spleeter\separator.py", line 265, in _separate_librosa
    sess = self._get_session()
  File "D:\SpleeterGUI_2.9.4.0\python\Lib\site-packages\spleeter\separator.py", line 240, in _get_session
    saver.restore(self._session, latest_checkpoint)
  File "D:\SpleeterGUI_2.9.4.0\python\Lib\site-packages\tensorflow\python\training\saver.py", line 1291, in restore
    raise ValueError("Can't load save_path when it is None.")
ValueError: Can't load save_path when it is None.
Finished processing all songs

Run complete
```
![image](https://github.com/boy1dr/SpleeterGui/assets/62152714/3cff838e-6822-44df-baeb-41bd8b909dc1)

@boy1dr

**Comment by boy1dr** [comment]
Error "Can't load save_path when it is None" occurs when Spleeter fails to load the pre-trained model files.
The easiest way to fix is to close SpleeterGUI, delete the "pre-trained_models" folder and run it again.

The model files are quite large and can become damaged while downloading on an unstable internet connection.
Antivirus apps may interfere here too. Because this is a windows executable that runs a python command line that downloads stuff, antivirus can block that as malicious. if the model files refuse to download, you *may* have to run SpleeterGUI with admin privileges or exclude the SpleeterGUI folder from it (whitelist).

https://github.com/deezer/spleeter/wiki/5.-FAQ#save-path-error

**Comment by Rexadev** [comment]
2.9.5 Working I was using 2.9.4
@boy1dr
