### ISSUE TITLE
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'F:" -p C:'

### ISSUE THREAD

**Issue by khunjiwon** [boy1dr/SpleeterGui#30]
Hi, I'm using a GUI from https://makenweb.com/spleeter2.php and keep getting this error at/near the end of processing:

```
Traceback (most recent call last):
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 193, in _run_module_as_main
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 85, in _run_code
  File "C:\Users\Jiwon\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 58, in <module>
    entrypoint()
  File "C:\Users\Jiwon\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 54, in entrypoint
    main(sys.argv)
  File "C:\Users\Jiwon\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 46, in main
    entrypoint(arguments, params)
  File "C:\Users\Jiwon\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\commands\separate.py", line 45, in entrypoint
    synchronous=False
  File "C:\Users\Jiwon\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\separator.py", line 220, in separate_to_file
    bitrate, synchronous)
  File "C:\Users\Jiwon\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\separator.py", line 257, in save_to_file
    os.makedirs(directory)
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\os.py", line 211, in makedirs
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\os.py", line 211, in makedirs
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\os.py", line 211, in makedirs
  [Previous line repeated 4 more times]
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\os.py", line 221, in makedirs
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'F:" -p C:'
Finished processing all songs
```

Hoping someone can shed some light on this. Thanks.

**Comment by boy1dr** [comment]
what is the output folder set to ?
looks like there might be some syntax issue with the text in the filepath

**Comment by khunjiwon** [comment]
Hi, there must be some sort of permission error on the original output folder as it worked perfectly after changing to a different location. So all is good now! Thank you for this amazing app!

**Comment by boy1dr** [comment]
Thanks for the update, glad it worked for you :)
