### ISSUE TITLE
cannot reshape array of size 0 into shape (0)

### ISSUE THREAD

**Issue by uncoolalx** [boy1dr/SpleeterGui#33]
quite a few files did not separate.

Traceback (most recent call last):
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 193, in _run_module_as_main
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 85, in _run_code
  File "C:\Users\SAMSUNG\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 58, in <module>
    entrypoint()
  File "C:\Users\SAMSUNG\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 54, in entrypoint
    main(sys.argv)
  File "C:\Users\SAMSUNG\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 46, in main
    entrypoint(arguments, params)
  File "C:\Users\SAMSUNG\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\commands\separate.py", line 45, in entrypoint
    synchronous=False
  File "C:\Users\SAMSUNG\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\separator.py", line 227, in separate_to_file
    sample_rate=self._sample_rate)
  File "C:\Users\SAMSUNG\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\audio\ffmpeg.py", line 109, in load
    waveform = np.frombuffer(buffer, dtype='<f4').reshape(-1, n_channels)
ValueError: cannot reshape array of size 0 into shape (0)
Traceback (most recent call last):
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 193, in _run_module_as_main
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 85, in _run_code
  File "C:\Users\SAMSUNG\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 58, in <module>
    entrypoint()
  File "C:\Users\SAMSUNG\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 54, in entrypoint
    main(sys.argv)
  File "C:\Users\SAMSUNG\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 46, in main
    entrypoint(arguments, params)
  File "C:\Users\SAMSUNG\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\commands\separate.py", line 45, in entrypoint
    synchronous=False
  File "C:\Users\SAMSUNG\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\separator.py", line 227, in separate_to_file
    sample_rate=self._sample_rate)
  File "C:\Users\SAMSUNG\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\audio\ffmpeg.py", line 109, in load
    waveform = np.frombuffer(buffer, dtype='<f4').reshape(-1, n_channels)
ValueError: cannot reshape array of size 0 into shape (0)
Processing E:\Tu Eres.mp3

Run complete

**Comment by uncoolalx** [comment]
corrupt files

**Comment by steadybright** [comment]
> corrupt files

indeed
