### ISSUE TITLE
Error Processing Music Files

### ISSUE THREAD

**Issue by Propblast** [boy1dr/SpleeterGui#47]
Everytime I try to process a music file I get the following script with errors. Can anyvody help?

Starting processing of all songs
Processing C:\Users\BIGCHUB\Desktop\7_ Macka B_Joe Ariwa - Warrior Style _Kunte Kinte__Warrior Dub.wav
Traceback (most recent call last):
  File "C:\Users\BIGCHUB\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\BIGCHUB\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\BIGCHUB\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\imp.py", line 242, in load_module
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\imp.py", line 342, in load_dynamic
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 193, in _run_module_as_main
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 85, in _run_code
  File "C:\Users\BIGCHUB\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 58, in <module>
    entrypoint()
  File "C:\Users\BIGCHUB\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 54, in entrypoint
    main(sys.argv)
  File "C:\Users\BIGCHUB\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 36, in main
    enable_logging()
  File "C:\Users\BIGCHUB\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\utils\logging.py", line 60, in enable_logging
    tf_logger = get_tensorflow_logger()
  File "C:\Users\BIGCHUB\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\utils\logging.py", line 27, in get_tensorflow_logger
    from tensorflow.compat.v1 import logging
  File "C:\Users\BIGCHUB\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\tensorflow\__init__.py", line 99, in <module>
    from tensorflow_core import *
  File "C:\Users\BIGCHUB\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\tensorflow_core\__init__.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\BIGCHUB\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\tensorflow\__init__.py", line 50, in __getattr__
    module = self._load()
  File "C:\Users\BIGCHUB\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\tensorflow\__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\__init__.py", line 127, in import_module
  File "C:\Users\BIGCHUB\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\tensorflow_core\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\BIGCHUB\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\BIGCHUB\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\BIGCHUB\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\BIGCHUB\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\imp.py", line 242, in load_module
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\imp.py", line 342, in load_dynamic
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.
Failed to load the native TensorFlow runtime.
See https://www.tensorflow.org/install/errors
for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
Finished processing all songs

Run complete

**Comment by boy1dr** [comment]
Hi there
The error says the tensorflow DLL failed to load. This normally occurs because the CPU in your computer does not have AVX which is required to run spleeter.
There is some more info here https://makenweb.com/spleeter_help.php as the top common problem.
Generally speaking, Intel Pentium or Celeron CPU's do not have AVX.
If you have one of those you might try one of the online versions of spleeter.
Otherwise, what CPU do you have? maybe i can find some more info on the problem for you.

**Comment by Propblast** [comment]
I'm running Windows 10 64-bit, AMD E2-3000M CPU, 8gig RAM, AMD Radeon HD 6380G

**Comment by boy1dr** [comment]
There isn't much data on the AMD E2-300M CPU that shows AVX support but i did find 1 website that showed comparison of CPU's and unfortunately this one does not have AVX support.
https://askgeek.io/en/cpus/vs/AMD_A6-5357M-vs-AMD_E2-3000M

Instruction sets such as AVX are hardware modules built in to the CPU that accelerate certain functions. The more affordable  CPU's will tend to lack some hardware support and rely on software to do these tasks. but without hardware acceleration will take much longer to perform the task.
Everyday tasks are as fast as the top end models but things like video encoding might not perform so well. in this case the AVX instruction set is a requirement of tensorflow AI that spleeter uses.

Here are some online versions of spleeter that you could use...
VocalRemover: https://vocalremover.org/
EZStems: https://ezstems.com/
Melodyml: https://melody.ml/

Dylan Tallchief recently made a video on those alternatives https://www.youtube.com/watch?v=JAg_Lzb6WVI

**Comment by spicefan25** [comment]
Hi everyone, i have the same problem but i don't have problem with AVX, i hope what the problem will be resolve with the version 2.9 of SpleeterGUI
<img width="314" alt="2020-10-25 01_56_02-AVXcheck" src="https://user-images.githubusercontent.com/73409549/97095857-47f9e700-1665-11eb-8a73-ee77277e2e3c.png">
