### ISSUE TITLE
Dont know what to do

### ISSUE THREAD

**Issue by Loxidante** [boy1dr/SpleeterGui#52]
i installed Spleetergui.
It opens and i can give it a ouput folder. when i drag a song in to it i see a bunch of code passing and say its  complete but its not.
here is the log. i am a compleet noob so please don't shoot me

Starting processing of all songs
Processing D:\spotify downloads\Q music foute party 2020\Cotton Eye Joe.mp3
Traceback (most recent call last):
  File "C:\Users\DJscy\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\DJscy\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\DJscy\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\imp.py", line 242, in load_module
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\imp.py", line 342, in load_dynamic
ImportError: DLL load failed: Een initialisatieroutine van de dynamic link library (DLL-bestand) is mislukt.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 193, in _run_module_as_main
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 85, in _run_code
  File "C:\Users\DJscy\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 58, in <module>
    entrypoint()
  File "C:\Users\DJscy\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 54, in entrypoint
    main(sys.argv)
  File "C:\Users\DJscy\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 36, in main
    enable_logging()
  File "C:\Users\DJscy\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\utils\logging.py", line 60, in enable_logging
    tf_logger = get_tensorflow_logger()
  File "C:\Users\DJscy\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\utils\logging.py", line 27, in get_tensorflow_logger
    from tensorflow.compat.v1 import logging
  File "C:\Users\DJscy\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\tensorflow\__init__.py", line 99, in <module>
    from tensorflow_core import *
  File "C:\Users\DJscy\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\tensorflow_core\__init__.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\DJscy\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\tensorflow\__init__.py", line 50, in __getattr__
    module = self._load()
  File "C:\Users\DJscy\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\tensorflow\__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\__init__.py", line 127, in import_module
  File "C:\Users\DJscy\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\tensorflow_core\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\DJscy\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\DJscy\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\DJscy\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\DJscy\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\imp.py", line 242, in load_module
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\imp.py", line 342, in load_dynamic
ImportError: DLL load failed: Een initialisatieroutine van de dynamic link library (DLL-bestand) is mislukt.
Failed to load the native TensorFlow runtime.
See https://www.tensorflow.org/install/errors
for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
Finished processing all songs

**Comment by boy1dr** [comment]
Near the end it mentions "DLL load failed"
This means tensorflow isn't able to run on your CPU.
There's some more info about it here https://makenweb.com/spleeter_help.php

Sent from my mobile thingy

________________________________

**Comment by Loxidante** [comment]
Thanks for the link. I think my cpu is to old for this. Gonna use the pc from my son and see what happens.
Thanks again for the reply and sorry for anwesering so late.

**Comment by boy1dr** [comment]
No worries. i have made a utility to check for AVX support which you can get from here.
https://makenweb.com/
AVXcheck

**Comment by Loxidante** [comment]
Oh thank you. You're the best. Gonna check this weekend. 👍👍👍
