### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by kall666** [boy1dr/SpleeterGui#63]
Starting processing of all songs
Processing F:\DL\JUNO.flac
Traceback (most recent call last):
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 193, in _run_module_as_main
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 85, in _run_code
  File "C:\Users\User\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 58, in <module>
    entrypoint()
  File "C:\Users\User\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 54, in entrypoint
    main(sys.argv)
  File "C:\Users\User\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 46, in main
    entrypoint(arguments, params)
  File "C:\Users\User\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\commands\separate.py", line 45, in entrypoint
    synchronous=False
  File "C:\Users\User\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\separator.py", line 231, in separate_to_file
    bitrate, synchronous)
  File "C:\Users\User\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\separator.py", line 270, in save_to_file
    os.makedirs(directory)
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\os.py", line 211, in makedirs
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\os.py", line 211, in makedirs
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\os.py", line 211, in makedirs
  [Previous line repeated 4 more times]
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\os.py", line 221, in makedirs
OSError: [WinError 123] 檔案名稱、目錄名稱或磁碟區標籤語法錯誤。: 'F:" -d 600 -p C:'
Finished processing all songs

Run complete

CPU i7 7700K with AVX AVX2
and i don't have D:\

**Comment by boy1dr** [comment]
@kall666 it appears to have had trouble creating the output folder.
The Chinese text translates to "The file name, directory name, or volume label syntax is incorrect.". 
Is your input file F:\DL\JUNO.flac ?
What is your output path?
What is your windows language set as?

FYI: the D: in the error messages seems to be from the spleeter developers machine. i don't have a D: either but when python has a fail it always seems to quote that drive path regardless of HDD volumes.

**Comment by kall666** [comment]
Thanks for Response
i find that can't output to F:/
need to output to F:/folder
now works perfect. 
sorry to disturb you with this stupid question  :(

**Comment by boy1dr** [comment]
no problem, not a stupid question i just never tested for that.
Glad you got it working :)

**Comment by tansro** [comment]
hello admin, let me ask what is this error, how to fix admin. Thank you.
  
File "C:\Users\PC NMT\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 28, in <module>
    self_check.preload_check()
  File "C:\Users\PC NMT\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\tensorflow\python\platform\self_check.py", line 61, in preload_check
    % " or ".join(missing))
ImportError: Could not find the DLL(s) 'msvcp140.dll or msvcp140_1.dll'. TensorFlow requires that these DLLs be installed in a directory that is named in your %PATH% environment variable. You may install these DLLs by downloading "Microsoft C++ Redistributable for Visual Studio 2015, 2017 and 2019" for your platform from this URL: https://support.microsoft.com/help/2977003/the-latest-supported-visual-c-downloads
Finished processing all songs

Run complete
![1](https://user-images.githubusercontent.com/65890487/96023591-dd82c300-0e7c-11eb-86e6-57f686707083.png)

**Comment by boy1dr** [comment]
@tansro There is a component missing from your windows. please install it from here https://aka.ms/vs/16/release/vc_redist.x64.exe
or use the link provided in your original post.

**Comment by Rith84** [comment]
Traceback (most recent call last):
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 193, in _run_module_as_main
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 85, in _run_code
  File "C:\Users\Admin\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 256, in <module>
    entrypoint()
  File "C:\Users\Admin\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 250, in entrypoint
    spleeter()
  File "C:\Users\Admin\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\typer\main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "C:\Users\Admin\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Admin\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Users\Admin\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Admin\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Admin\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\Admin\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\typer\main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "C:\Users\Admin\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 107, in separate
    from .audio.adapter import AudioAdapter
  File "C:\Users\Admin\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\audio\adapter.py", line 14, in <module>
    import tensorflow as tf
  File "C:\Users\Admin\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\tensorflow\__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\Admin\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\tensorflow\python\__init__.py", line 40, in <module>
    from tensorflow.python.eager import context
  File "C:\Users\Admin\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\tensorflow\python\eager\context.py", line 35, in <module>
    from tensorflow.python import pywrap_tfe
  File "C:\Users\Admin\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\tensorflow\python\pywrap_tfe.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\Admin\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 28, in <module>
    self_check.preload_check()
  File "C:\Users\Admin\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\tensorflow\python\platform\self_check.py", line 61, in preload_check
    % " or ".join(missing))
ImportError: Could not find the DLL(s) 'msvcp140_1.dll'. TensorFlow requires that these DLLs be installed in a directory that is named in your %PATH% environment variable. You may install these DLLs by downloading "Microsoft C++ Redistributable for Visual Studio 2015, 2017 and 2019" for your platform from this URL: https://support.microsoft.com/help/2977003/the-latest-supported-visual-c-downloads
Finished processing all songs

Run complete

(https://user-images.githubusercontent.com/59683590/128865295-fd22a086-9c74-469e-9dc0-47ec1ee3bfa5.png)

**Comment by boy1dr** [comment]
@Rith84 Please see previous comment for exactly the same problem and the solution.

**Comment by Rith84** [comment]
> @Rith84 Please see previous comment for exactly the same problem and the solution.

I know! So, I have installed that requires software but it still not working

**Comment by Rith84** [comment]
> @Rith84 Please see previous comment for exactly the same problem and the solution.

Look at this 


![Annotation 2021-08-10 190845.png](https://user-images.githubusercontent.com/59683590/128952423-207112c0-807a-4c71-9590-97a5713fa7da.png)

**Comment by Rith84** [comment]
> @Rith84 that's odd it hasn't fixed it. the error message you provided has the link for the missing component.
> https://support.microsoft.com/help/2977003/the-latest-supported-visual-c-downloads
> 
> I found some more detail over on stackoverflow
> https://stackoverflow.com/questions/60157335/cant-pip-install-tensorflow-msvcp140-1-dll-missing

Thanks! Now it work and I've update it in my language (Khmer Language of Cambodia 🇰🇭) Thank you 🙏

![IMG_20210812_072933.jpg](https://user-images.githubusercontent.com/59683590/129120447-0b04ae04-8e8e-49d9-8b0d-7895c2afd6ee.jpg)
