### ISSUE TITLE
DtypeObj Error

### ISSUE THREAD

**Issue by slavaspo** [boy1dr/SpleeterGui#64]
File "C:\Users\sspon\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\pandas\core\arrays\sparse\accessor.py", line 10, in <module>
    from pandas.core.arrays.sparse.array import SparseArray
  File "C:\Users\sspon\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\pandas\core\arrays\sparse\array.py", line 44, in <module>
    from pandas.core.arrays.sparse.dtype import SparseDtype
  File "C:\Users\sspon\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\pandas\core\arrays\sparse\dtype.py", line 9, in <module>
    from pandas._typing import Dtype, DtypeObj
ImportError: cannot import name 'DtypeObj' from 'pandas._typing' (C:\Users\sspon\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\pandas\_typing.py)
Finished processing all songs

**Comment by boy1dr** [comment]
I haven't seen that error before and a quick google search doesn't turn up anything obvious.
Maybe try re-installing it.
If you have Windows Defender settings cranked up or other antivirus/firewall software this can also interfere with python doing it's thing. Perhaps try installing it as admin (right click installer and run-as-admin)

**Comment by slavaspo** [comment]
It didn't help. It was working on my old PC, but I just upgrade to 9900K CPU.

**Comment by boy1dr** [comment]
hmm i really don't know what could cause that :( 
I will give you some commands to paste in to a command window, if you can run them and if it still doesn't work copy back the text here so i can see whats going wrong for you.
replace "YOUR-NAME" with your username....

cd C:\Users\YOUR-NAME\AppData\Roaming\SpleeterGUI\python
python -m pip install spleeter --upgrade

**Comment by slavaspo** [comment]
It didn't work. Here's my code from Spleeter
Starting processing of all songs
Processing C:\Users\sspon\Downloads\RAYE-Natalie Don't\RAYE-Natalie Don't.mp3
Traceback (most recent call last):
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 193, in _run_module_as_main
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 85, in _run_code
  File "C:\Users\sspon\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 58, in <module>
    entrypoint()
  File "C:\Users\sspon\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 54, in entrypoint
    main(sys.argv)
  File "C:\Users\sspon\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 40, in main
    from .commands.separate import entrypoint
  File "C:\Users\sspon\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\commands\separate.py", line 15, in <module>
    from ..separator import Separator
  File "C:\Users\sspon\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\separator.py", line 28, in <module>
    from .audio.convertor import to_stereo
  File "C:\Users\sspon\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\audio\convertor.py", line 11, in <module>
    from ..utils.tensor import from_float32_to_uint8, from_uint8_to_float32
  File "C:\Users\sspon\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\utils\tensor.py", line 8, in <module>
    import pandas as pd
  File "C:\Users\sspon\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\pandas\__init__.py", line 55, in <module>
    from pandas.core.api import (
  File "C:\Users\sspon\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\pandas\core\api.py", line 23, in <module>
    from pandas.core.arrays import Categorical, array
  File "C:\Users\sspon\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\pandas\core\arrays\__init__.py", line 13, in <module>
    from .sparse import SparseArray  # noqa: F401
  File "C:\Users\sspon\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\pandas\core\arrays\sparse\__init__.py", line 3, in <module>
    from pandas.core.arrays.sparse.accessor import SparseAccessor, SparseFrameAccessor
  File "C:\Users\sspon\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\pandas\core\arrays\sparse\accessor.py", line 10, in <module>
    from pandas.core.arrays.sparse.array import SparseArray
  File "C:\Users\sspon\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\pandas\core\arrays\sparse\array.py", line 44, in <module>
    from pandas.core.arrays.sparse.dtype import SparseDtype
  File "C:\Users\sspon\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\pandas\core\arrays\sparse\dtype.py", line 9, in <module>
    from pandas._typing import Dtype, DtypeObj
ImportError: cannot import name 'DtypeObj' from 'pandas._typing' (C:\Users\sspon\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\pandas\_typing.py)
Finished processing all songs

Run complete

**Comment by slavaspo** [comment]
This app works only on old computers. I just installed it on my old laptop and it's working. It doesn't work on my new  i9 machine. I think you and users of this app should know about this issue.

**Comment by boy1dr** [comment]
@slavaspo which i9 processor do you have?

**Comment by slavaspo** [comment]
9900K

**Comment by boy1dr** [comment]
looks like other spleeter uses have run in to this issue too, an upgrade may fix it, sorry i can't make this next bit easier for you.

open cmd.exe
paste these next two lines (separately)
cd C:\Users\sspon\AppData\Roaming\SpleeterGUI\python
python -m pip install --upgrade pandas

i tried this on my machine and it uninstalled 1.1.2 and installed 1.1.4
and spleeter still works ok even though it gave a warning.

**Comment by slavaspo** [comment]
It didn't help.
Here's what I see:

Starting processing of all songs
Processing C:\Users\sspon\Downloads\Михаил Шуфутинский-Боксёрская любовь\Михаил Шуфутинский-Боксёрская любовь.mp3
Traceback (most recent call last):
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 193, in _run_module_as_main
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 85, in _run_code
  File "C:\Users\sspon\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 58, in <module>
    entrypoint()
  File "C:\Users\sspon\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 54, in entrypoint
    main(sys.argv)
  File "C:\Users\sspon\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 46, in main
    entrypoint(arguments, params)
  File "C:\Users\sspon\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\commands\separate.py", line 34, in entrypoint
    stft_backend=arguments.stft_backend)
  File "C:\Users\sspon\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\separator.py", line 109, in __init__
    self._params['stft_backend'] = get_backend(stft_backend)
  File "C:\Users\sspon\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\separator.py", line 74, in get_backend
    if len(tf.config.list_physical_devices('GPU')):
  File "C:\Users\sspon\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\tensorflow_core\python\util\module_wrapper.py", line 193, in __getattr__
    attr = getattr(self._tfmw_wrapped_module, name)
AttributeError: module 'tensorflow._api.v1.config' has no attribute 'list_physical_devices'
Finished processing all songs

Run complete

**Comment by boy1dr** [comment]
at least it's a different error, now it is complaining that it can't enumerate available GPU's.
are you trying to run spleeter-gpu ??

**Comment by slavaspo** [comment]
I'm no sure what "run spleeter-gpu" means.

**Comment by boy1dr** [comment]
spleeter uses AI called Tensorflow. it can use CPU or GPU. the latest error is more related to GPU but the base install of spleeter is for CPU.
There seems to be something really wrong here and i'm not a python expert so i don't know how to help sorry.
Such is the way of free software, it works for most but there are always edge cases the don't.

if a fresh copy and install doesn't work (download could have been damaged) you will just have to use one of the online ones.
sorry it didn't work out.

**Comment by boy1dr** [comment]
i have just posted an updated version of the spleeter/python bundle, hopefully this sorts out your problems
https://makenweb.com/SpleeterGUI

**Comment by slavaspo** [comment]
It crashes my machine.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by boy1dr** [comment]
i'm sorry i don't know why it's crashing your machine. this project gets downloaded over 4000 times every month and crashing isn't something i hear about from those using it.
You might need to dig a little deeper into the windows event viewer (see Windows logs\Application) maybe there is mention in there about what is causing the crashes.

**Comment by SaoYear** [comment]
Here is my solution: Go to `miniconda3/envs/YOUR_ENV_NAME/lib/python3.8/site-packages/`, delete all `pandas` packages and reinstall the package by
```
pip install pandas
```

**Comment by boy1dr** [comment]
@SaoYear Thanks for the tip!
Where you having this same error? and is it working fine now after pandas re-install?

**Comment by SaoYear** [comment]
> @SaoYear Thanks for the tip!
> Where you having this same error? and is it working fine now after pandas re-install?

This error happened when I wrongly re-install my conda environment by a requirement.txt, where another version of pandas was installed. After that, I want to recover the pandas to the latest version. Then, the error occurred.

Now its working fine for me. 

Thanks for your response!
