### ISSUE TITLE
Obj崩溃

### ISSUE THREAD

**Issue by EAIYHAY** [boy1dr/SpleeterGui#68]
Traceback (most recent call last):
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 193, in _run_module_as_main
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 85, in _run_code
  File "C:\Users\EAIYHAY\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 58, in <module>
    entrypoint()
  File "C:\Users\EAIYHAY\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 54, in entrypoint
    main(sys.argv)
  File "C:\Users\EAIYHAY\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 40, in main
    from .commands.separate import entrypoint
  File "C:\Users\EAIYHAY\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\commands\separate.py", line 15, in <module>
    from ..separator import Separator
  File "C:\Users\EAIYHAY\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\separator.py", line 28, in <module>
    from .audio.convertor import to_stereo
  File "C:\Users\EAIYHAY\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\audio\convertor.py", line 11, in <module>
    from ..utils.tensor import from_float32_to_uint8, from_uint8_to_float32
  File "C:\Users\EAIYHAY\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\utils\tensor.py", line 8, in <module>
    import pandas as pd
  File "C:\Users\EAIYHAY\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\pandas\__init__.py", line 55, in <module>
    from pandas.core.api import (
  File "C:\Users\EAIYHAY\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\pandas\core\api.py", line 23, in <module>
    from pandas.core.arrays import Categorical, array
  File "C:\Users\EAIYHAY\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\pandas\core\arrays\__init__.py", line 13, in <module>
    from .sparse import SparseArray  # noqa: F401
  File "C:\Users\EAIYHAY\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\pandas\core\arrays\sparse\__init__.py", line 3, in <module>
    from pandas.core.arrays.sparse.accessor import SparseAccessor, SparseFrameAccessor
  File "C:\Users\EAIYHAY\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\pandas\core\arrays\sparse\accessor.py", line 10, in <module>
    from pandas.core.arrays.sparse.array import SparseArray
  File "C:\Users\EAIYHAY\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\pandas\core\arrays\sparse\array.py", line 44, in <module>
    from pandas.core.arrays.sparse.dtype import SparseDtype
  File "C:\Users\EAIYHAY\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\pandas\core\arrays\sparse\dtype.py", line 9, in <module>
    from pandas._typing import Dtype, DtypeObj
ImportError: cannot import name 'DtypeObj' from 'pandas._typing' (C:\Users\EAIYHAY\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\pandas\_typing.py)

**Comment by boy1dr** [comment]
not sure what the problem is, was that all the output it had ?
seems to be missing the bottom section that describes the error.

**Comment by EAIYHAY** [comment]
更新出现的问题 1.5.4可以正常使用 点击更新以后 到 显示 spleeter 版本...
Name: spleeter
Version: 2.0.1
出现的问题 多次重装无果 安装2.6版本问题同样出现
老电脑1.5.4版本可以正常运行

**Comment by EAIYHAY** [comment]
开始处理所有歌曲
处理中 C:\Users\EAIYHAY\Desktop\金郑建 这份恩情报不完 伴奏 无人声.flac
Traceback (most recent call last):
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 193, in _run_module_as_main
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 85, in _run_code
  File "C:\Users\EAIYHAY\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 58, in <module>
    entrypoint()
  File "C:\Users\EAIYHAY\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 54, in entrypoint
    main(sys.argv)
  File "C:\Users\EAIYHAY\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 40, in main
    from .commands.separate import entrypoint
  File "C:\Users\EAIYHAY\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\commands\separate.py", line 15, in <module>
    from ..separator import Separator
  File "C:\Users\EAIYHAY\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\separator.py", line 28, in <module>
    from .audio.convertor import to_stereo
  File "C:\Users\EAIYHAY\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\audio\convertor.py", line 11, in <module>
    from ..utils.tensor import from_float32_to_uint8, from_uint8_to_float32
  File "C:\Users\EAIYHAY\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\utils\tensor.py", line 8, in <module>
    import pandas as pd
  File "C:\Users\EAIYHAY\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\pandas\__init__.py", line 55, in <module>
    from pandas.core.api import (
  File "C:\Users\EAIYHAY\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\pandas\core\api.py", line 23, in <module>
    from pandas.core.arrays import Categorical, array
  File "C:\Users\EAIYHAY\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\pandas\core\arrays\__init__.py", line 13, in <module>
    from .sparse import SparseArray  # noqa: F401
  File "C:\Users\EAIYHAY\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\pandas\core\arrays\sparse\__init__.py", line 3, in <module>
    from pandas.core.arrays.sparse.accessor import SparseAccessor, SparseFrameAccessor
  File "C:\Users\EAIYHAY\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\pandas\core\arrays\sparse\accessor.py", line 10, in <module>
    from pandas.core.arrays.sparse.array import SparseArray
  File "C:\Users\EAIYHAY\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\pandas\core\arrays\sparse\array.py", line 44, in <module>
    from pandas.core.arrays.sparse.dtype import SparseDtype
  File "C:\Users\EAIYHAY\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\pandas\core\arrays\sparse\dtype.py", line 9, in <module>
    from pandas._typing import Dtype, DtypeObj
ImportError: cannot import name 'DtypeObj' from 'pandas._typing' (C:\Users\EAIYHAY\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\pandas\_typing.py)
完成处理所有歌曲

运行完成

**Comment by EAIYHAY** [comment]
Starting processing of all songs
Processing C:\Users\EAIYHAY\Desktop\蓝眼睛演唱组 小路 伴奏.mp3
Name: spleeter
Version: 2.0.1
Finished processing all songs

Run complete
Traceback (most recent call last):
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 193, in _run_module_as_main
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 85, in _run_code
  File "C:\Users\EAIYHAY\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 58, in <module>
    entrypoint()
  File "C:\Users\EAIYHAY\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 54, in entrypoint
    main(sys.argv)
  File "C:\Users\EAIYHAY\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 40, in main
    from .commands.separate import entrypoint
  File "C:\Users\EAIYHAY\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\commands\separate.py", line 15, in <module>
    from ..separator import Separator
  File "C:\Users\EAIYHAY\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\separator.py", line 28, in <module>
    from .audio.convertor import to_stereo
  File "C:\Users\EAIYHAY\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\audio\convertor.py", line 11, in <module>
    from ..utils.tensor import from_float32_to_uint8, from_uint8_to_float32
  File "C:\Users\EAIYHAY\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\utils\tensor.py", line 8, in <module>
    import pandas as pd
  File "C:\Users\EAIYHAY\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\pandas\__init__.py", line 55, in <module>
    from pandas.core.api import (
  File "C:\Users\EAIYHAY\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\pandas\core\api.py", line 23, in <module>
    from pandas.core.arrays import Categorical, array
  File "C:\Users\EAIYHAY\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\pandas\core\arrays\__init__.py", line 13, in <module>
    from .sparse import SparseArray  # noqa: F401
  File "C:\Users\EAIYHAY\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\pandas\core\arrays\sparse\__init__.py", line 3, in <module>
    from pandas.core.arrays.sparse.accessor import SparseAccessor, SparseFrameAccessor
  File "C:\Users\EAIYHAY\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\pandas\core\arrays\sparse\accessor.py", line 10, in <module>
    from pandas.core.arrays.sparse.array import SparseArray
  File "C:\Users\EAIYHAY\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\pandas\core\arrays\sparse\array.py", line 44, in <module>
    from pandas.core.arrays.sparse.dtype import SparseDtype
  File "C:\Users\EAIYHAY\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\pandas\core\arrays\sparse\dtype.py", line 9, in <module>
    from pandas._typing import Dtype, DtypeObj
ImportError: cannot import name 'DtypeObj' from 'pandas._typing' (C:\Users\EAIYHAY\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\pandas\_typing.py)

Run complete

**Comment by boy1dr** [comment]
Python seems to be having some troubles running. if this is the first song you have tried to process, maybe uninstall it, download it again and re-install using a fresh download.
it is a big download and i have seen some corruption occur, fresh install seemed to fix it.
otherwise i'm not sure what would cause this problem. i'm not a python expert and a quick google search didn't reveal anything.

**Comment by EAIYHAY** [comment]
Google和baidu搜索没有发现任何信息
 已经重装了两次SpleeterGUI_V2.8 问题依旧存在
电脑没有进行其他任何设置
是否需要安装Python？
安装Python后可能会解决问题吗？
![image](https://user-images.githubusercontent.com/73930602/98089754-2ba84680-1ebe-11eb-9868-b99b8e4601b4.png)

**Comment by EAIYHAY** [comment]
- [ ] 
![Uploading F7P7[][7}$O5T8X8KOVBZ$N.png…]()

**Comment by boy1dr** [comment]
try creating a folder on your desktop to output the songs to. i have seen people have issues outputting directly to desktop and c:\

**Comment by EAIYHAY** [comment]
> 尝试在桌面上创建一个文件夹以将歌曲输出到该文件夹​​。我已经看到人们在直接输出到桌面和c时遇到问题：\

![6SL_@9D%OP}8$S00X`5U~U6](https://user-images.githubusercontent.com/73930602/98090409-f2240b00-1ebe-11eb-9f01-ad16106f4d30.png)
问题依然存在
我也不清楚哪里出问题了

**Comment by boy1dr** [comment]
looks like other spleeter uses have run in to this issue, an upgrade may fix it, sorry i can't make this next bit easier for you.

open cmd.exe
paste these next two lines (separately)
cd C:\Users\EAIYHAY\AppData\Roaming\SpleeterGUI\python
python -m pip install --upgrade pandas

**Comment by EAIYHAY** [comment]
粘贴以后问题没有得到解决 反应无效
360错误识别为木马Generic/Trojan.d86
木马名称：Generic/Trojan.d86
所在路径：C:\Users\EAIYHAY\AppData\Roaming\SpleeterGUI\SpleeterGui\obj\Release\SpleeterGui.exe
![Uploading image.png…]()

**Comment by EAIYHAY** [comment]
我发现另外一个帖子里面也有一个人发生了相同的问题 我和他应该是一样的！

**Comment by EAIYHAY** [comment]
开始处理所有歌曲
处理中 C:\Users\EAIYHAY\Desktop\+2.flac
Traceback (most recent call last):
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 193, in _run_module_as_main
  File "C:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 85, in _run_code
  File "C:\Users\EAIYHAY\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 58, in <module>
    entrypoint()
  File "C:\Users\EAIYHAY\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 54, in entrypoint
    main(sys.argv)
  File "C:\Users\EAIYHAY\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 46, in main
    entrypoint(arguments, params)
  File "C:\Users\EAIYHAY\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\commands\separate.py", line 45, in entrypoint
    synchronous=False
  File "C:\Users\EAIYHAY\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\separator.py", line 231, in separate_to_file
    bitrate, synchronous)
  File "C:\Users\EAIYHAY\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\separator.py", line 270, in save_to_file
    os.makedirs(directory)
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\os.py", line 211, in makedirs
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\os.py", line 211, in makedirs
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\os.py", line 211, in makedirs
  [Previous line repeated 4 more times]
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\os.py", line 221, in makedirs
OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: 'C:" -d 600 -p C:'
完成处理所有歌曲

**Comment by EAIYHAY** [comment]
C:\Users\EAIYHAY>cd c：\Users\EAIYHAY\AppData\Roaming\SpleeterGUI\python
系统找不到指定的路径。

**Comment by EAIYHAY** [comment]
重装了一个2.5版本的
显示
Starting processing of all songs
Processing C:\Users\EAIYHAY\Desktop\王亮 拥措 云上理塘 伴奏 无人声.mp3
INFO:spleeter:Downloading model archive https://github.com/deezer/spleeter/releases/download/v1.4.0/2stems.tar.gz
Traceback (most recent call last):
  File "C:\Users\EAIYHAY\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\urllib3\response.py", line 425, in _error_catcher
    yield
  File "C:\Users\EAIYHAY\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\urllib3\response.py", line 507, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\client.py", line 457, in read
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\client.py", line 501, in readinto
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\socket.py", line 589, in readinto
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\ssl.py", line 1071, in recv_into
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\ssl.py", line 929, in read
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Users\EAIYHAY\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\requests\models.py", line 750, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "C:\Users\EAIYHAY\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\urllib3\response.py", line 564, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "C:\Users\EAIYHAY\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\urllib3\response.py", line 529, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\contextlib.py", line 130, in __exit__
  File "C:\Users\EAIYHAY\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\urllib3\response.py", line 443, in _error_catcher
    raise ProtocolError("Connection broken: %r" % e, e)
urllib3.exceptions.ProtocolError: ("Connection broken: ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None)", ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 193, in _run_module_as_main
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 85, in _run_code
  File "C:\Users\EAIYHAY\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 58, in <module>
    entrypoint()
  File "C:\Users\EAIYHAY\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 54, in entrypoint
    main(sys.argv)
  File "C:\Users\EAIYHAY\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 46, in main
    entrypoint(arguments, params)
  File "C:\Users\EAIYHAY\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\commands\separate.py", line 45, in entrypoint
    synchronous=False
  File "C:\Users\EAIYHAY\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\separator.py", line 217, in separate_to_file
    sources = self.separate(waveform, audio_descriptor)
  File "C:\Users\EAIYHAY\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\separator.py", line 184, in separate
    return self._separate_librosa(waveform, audio_descriptor)
  File "C:\Users\EAIYHAY\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\separator.py", line 157, in _separate_librosa
    latest_checkpoint = tf.train.latest_checkpoint(get_default_model_dir(self._params['model_dir']))
  File "C:\Users\EAIYHAY\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\utils\estimator.py", line 31, in get_default_model_dir
    return model_provider.get(model_dir)
  File "C:\Users\EAIYHAY\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\model\provider\__init__.py", line 67, in get
    model_directory)
  File "C:\Users\EAIYHAY\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\model\provider\github.py", line 101, in download
    for chunk in response.iter_content(chunk_size=8192):
  File "C:\Users\EAIYHAY\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\requests\models.py", line 753, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ("Connection broken: ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None)", ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
Finished processing all songs

Run complete

**Comment by boy1dr** [comment]
@EAIYHAY looks like your internet connection wasn't available "ConnectionResetError"
