### ISSUE TITLE
[ImportError: cannot import name 'DtypeObj' from 'pandas._typing'] on song process traceback

### ISSUE THREAD

**Issue by exosilver** [boy1dr/SpleeterGui#69]
This error occurred after I clicked "Spleeter core upgrade" under Help. I have been using spleeterGUI successfully for months, and suddenly it hasn't been creating files when the task is finished (a simple printout of "started processing, processing, finished, run complete. No traceback.) I upgraded the core within the program, and now I am getting this:
```
Starting processing of all songs
Processing F:\Deemix Music\song.flac
Traceback (most recent call last):
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 193, in _run_module_as_main
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 85, in _run_code
  File "C:\Users\exo\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 58, in <module>
    entrypoint()
  File "C:\Users\exo\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 54, in entrypoint
    main(sys.argv)
  File "C:\Users\exo\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 40, in main
    from .commands.separate import entrypoint
  File "C:\Users\exo\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\commands\separate.py", line 15, in <module>
    from ..separator import Separator
  File "C:\Users\exo\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\separator.py", line 28, in <module>
    from .audio.convertor import to_stereo
  File "C:\Users\exo\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\audio\convertor.py", line 11, in <module>
    from ..utils.tensor import from_float32_to_uint8, from_uint8_to_float32
  File "C:\Users\exo\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\utils\tensor.py", line 8, in <module>
    import pandas as pd
  File "C:\Users\exo\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\pandas\__init__.py", line 55, in <module>
    from pandas.core.api import (
  File "C:\Users\exo\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\pandas\core\api.py", line 23, in <module>
    from pandas.core.arrays import Categorical, array
  File "C:\Users\exo\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\pandas\core\arrays\__init__.py", line 13, in <module>
    from .sparse import SparseArray  # noqa: F401
  File "C:\Users\exo\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\pandas\core\arrays\sparse\__init__.py", line 3, in <module>
    from pandas.core.arrays.sparse.accessor import SparseAccessor, SparseFrameAccessor
  File "C:\Users\exo\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\pandas\core\arrays\sparse\accessor.py", line 10, in <module>
    from pandas.core.arrays.sparse.array import SparseArray
  File "C:\Users\exo\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\pandas\core\arrays\sparse\array.py", line 44, in <module>
    from pandas.core.arrays.sparse.dtype import SparseDtype
  File "C:\Users\exo\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\pandas\core\arrays\sparse\dtype.py", line 9, in <module>
    from pandas._typing import Dtype, DtypeObj
ImportError: cannot import name 'DtypeObj' from 'pandas._typing' (C:\Users\exo\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\pandas\_typing.py)
Finished processing all songs

Run complete
```

I have tried moving the file to C:, as well as using a .mp3 version, and the output is set to go to C:\Users\exo\Desktop\spleeter, which remains empty. A couple of other people have been having issues lately related to DtypeObj errors lately so it may have to do with the spleeter core upgrade.

**Comment by boy1dr** [comment]
@exosilver there are now 3 open issues with this same problem, you can check these to see if there are helpful comments in there.
It looks like spleeter needs an update, try this

open cmd.exe
paste these next two lines (separately) and change YOURNAME to your user account name.

  cd C:\Users\YOURNAME\AppData\Roaming\SpleeterGUI\python
  python -m pip install --upgrade pandas

if it's still not working type this one (kinda the same as the spleeter core upgrade)
  python -m pip install --upgrade spleeter

**Comment by jerrylive365** [comment]
@boy1dr 
Your instructions worked for me. Thank you very much!

**Comment by boy1dr** [comment]
glad to hear 👍 
i'm uploading a refresh of V2.8 to include this fix tonight. thanks for letting me know :)
