### ISSUE TITLE
After Spleeter installation, despite the fact that AVX Check = Yes, I get ImportError: DLL load failed: The specified module could not be found.

### ISSUE THREAD

**Issue by titust1** [boy1dr/SpleeterGui#72]
Hi Chris. Any idea?????? After Spleeter installation, despite the fact that AVX Check = Yes, I get the following
Processing C:\Users\Titus\Portable_Apps\Spleeter\a.mp3
Traceback (most recent call last):
  File "C:\Users\Titus\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed: The specified module could not be found.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 193, in _run_module_as_main
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 85, in _run_code
  File "C:\Users\Titus\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 58, in <module>
    entrypoint()
  File "C:\Users\Titus\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 54, in entrypoint
    main(sys.argv)
  File "C:\Users\Titus\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 36, in main
    enable_logging()
  File "C:\Users\Titus\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\utils\logging.py", line 60, in enable_logging
    tf_logger = get_tensorflow_logger()
  File "C:\Users\Titus\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\utils\logging.py", line 27, in get_tensorflow_logger
    from tensorflow.compat.v1 import logging
  File "C:\Users\Titus\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\tensorflow\__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\Titus\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\tensorflow\python\__init__.py", line 40, in <module>
    from tensorflow.python.eager import context
  File "C:\Users\Titus\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\tensorflow\python\eager\context.py", line 35, in <module>
    from tensorflow.python import pywrap_tfe
  File "C:\Users\Titus\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\tensorflow\python\pywrap_tfe.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\Titus\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 83, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\Titus\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed: The specified module could not be found.
Failed to load the native TensorFlow runtime.
See https://www.tensorflow.org/install/errors
for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
Finished processing all songs

**Comment by boy1dr** [comment]
hmm that's not good, i thought the AVX check was all that was needed to resolve this issue :(  
What CPU do you have in your computer?

**Comment by titust1** [comment]
Core i7 6700K
But my GPU is AMD and doesn’t have cuda.
Does it matter?

**Comment by boy1dr** [comment]
That CPU should run it. at work have a i7-8700 at work and it's fine there.
doesn't matter if you have AMD GPU, the spleeter i packaged uses the CPU.
will look in to it further for you tonight

**Comment by titust1** [comment]
Thanks a lot Chris,
I really appreciate your help.

Titus

------ Original Message ------

**Comment by mbelloc** [comment]
Got the same problem as @titust1
Tensorflow 1.15 and 2+ requires visual c++ 2019 redistributables for both 32 and 64 bits architectures.
Here are the links to download them: 

- https://aka.ms/vs/16/release/vc_redist.x86.exe
- https://aka.ms/vs/16/release/vc_redist.x64.exe

This solved the DLL load failed

**Comment by boy1dr** [comment]
@mbelloc thanks for providing the links, you should only need the 64bit version.
This and other help is available on my site https://makenweb.com/spleeter_help.php

**Comment by titust1** [comment]
thanks
