### ISSUE TITLE
TensorFlow Error

### ISSUE THREAD

**Issue by jayo2005** [boy1dr/SpleeterGui#94]
Using version 2.9

I get the below error

`Starting processing of all songs
Processing C:\Users\RDS Computers\Music\Roy Orbison - You Got It (Audio).mp3
Traceback (most recent call last):
  File "C:\Users\RDS Computers\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 193, in _run_module_as_main
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 85, in _run_code
  File "C:\Users\RDS Computers\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 256, in <module>
    entrypoint()
  File "C:\Users\RDS Computers\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 250, in entrypoint
    spleeter()
  File "C:\Users\RDS Computers\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\typer\main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "C:\Users\RDS Computers\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\RDS Computers\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Users\RDS Computers\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\RDS Computers\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\RDS Computers\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\RDS Computers\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\typer\main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "C:\Users\RDS Computers\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\__main__.py", line 107, in separate
    from .audio.adapter import AudioAdapter
  File "C:\Users\RDS Computers\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\spleeter\audio\adapter.py", line 14, in <module>
    import tensorflow as tf
  File "C:\Users\RDS Computers\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\tensorflow\__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\RDS Computers\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\tensorflow\python\__init__.py", line 40, in <module>
    from tensorflow.python.eager import context
  File "C:\Users\RDS Computers\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\tensorflow\python\eager\context.py", line 35, in <module>
    from tensorflow.python import pywrap_tfe
  File "C:\Users\RDS Computers\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\tensorflow\python\pywrap_tfe.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\RDS Computers\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 83, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\RDS Computers\AppData\Roaming\SpleeterGUI\python\Lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.
Failed to load the native TensorFlow runtime.
See https://www.tensorflow.org/install/errors
for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
Finished processing all songs

Run complete`

**Comment by boy1dr** [comment]
Hi Jayo
The error message is "ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed."
6 lines from the bottom.
This is the # 1 issue on the Help/FAQ page https://makenweb.com/spleeter_help
You CPU lacking AVX support is the top reason this error occurs but apparently there could be other reasons i have yet to determine. this utility with check for you https://makenweb.com/downloads/AVXcheck.zip

**Comment by jayo2005** [comment]
Thanks for the quick response. You are right my CPU does not have AVX support. I'll try it on my laptop
